import type {
  AccountOrder,
  CustomerProfile,
  EarningsRenderData,
  MessagesRenderData,
  MaterialAdvance,
  OrderDetailRenderData,
  PayoutRenderData,
  ProfileRenderData,
  ShopRenderData,
  TailorProfile,
} from '../shared/account-data-contracts'
import {
  emptyMessagesSurfaceData,
  emptyOrderDetailSurfaceData,
} from '../shared/account-empty-data'
import type { AccountDispatchState } from '../orders/account-dispatch-card'

const customerId = 'preview-customer'
const tailorUserId = 'preview-tailor-user'
const tailorProfileId = 'preview-tailor-profile'

export const previewOrder: AccountOrder = {
  id: 'preview-order',
  reference: 'DRP-PREVIEW-1042',
  order_kind: 'CUSTOM',
  garment_type: 'Two-piece set',
  item_title: null,
  item_size: null,
  garment_description: 'Emerald occasion set with a structured jacket and wide-leg trousers.',
  occasion: 'Birthday dinner',
  stage: 'SEWING',
  delivery_method: 'LOCAL_DELIVERY',
  delivery_address: 'Lagos, Nigeria',
  recipient_name: 'Amara',
  recipient_phone: null,
  fabric_source: 'TAILOR_SOURCES',
  fabric_funding_policy_version: null,
  special_note: null,
  fabric_tracking: null,
  tracking_number: null,
  carrier: null,
  fulfillment_provider: null,
  fulfillment_reference: null,
  fulfillment_contact_name: null,
  fulfillment_contact_phone: null,
  reference_photos: null,
  customer_measurements_snapshot: { bust: 92, waist: 74, hips: 101 },
  quoted_amount: 185000,
  subtotal_amount: 185000,
  fulfillment_fee: 10000,
  shipping_amount: 10000,
  tax_amount: 0,
  import_tax_amount: 0,
  duty_amount: 0,
  tax_collection_mode: 'COLLECTED_AT_CHECKOUT',
  tax_responsible_party: 'DRAPEON_MARKETPLACE_FACILITATOR',
  tax_rate_bps: 0,
  tax_region: 'NG',
  tax_fallback: false,
  platform_fee_amount: 18500,
  total_amount: 195000,
  currency: 'NGN',
  quoted_currency: 'NGN',
  created_at: '2026-09-18T12:00:00.000Z',
  updated_at: '2026-09-22T15:30:00.000Z',
  deadline: '2026-10-10T12:00:00.000Z',
  quoted_completion_date: '2026-10-06T12:00:00.000Z',
  quote_expires_at: null,
  customer_id: customerId,
  tailor_id: tailorUserId,
  tailor_profile_id: tailorProfileId,
  seller_item_id: null,
  payment_provider: 'PAYSTACK',
  fulfillment_payment_requested_at: null,
  fulfillment_payment_paid_at: null,
  fulfillment_payment_provider: null,
  fulfillment_payment_intent_id: null,
  fulfillment_payment_checkout_url: null,
  consultation_fee: 0,
  video_call_url: null,
  escrow_released: false,
  auto_release_at: null,
  collection_code: null,
  collection_code_expiry: null,
  collection_code_used: false,
  active_quote_id: null,
  active_quote_version: 1,
  negotiation_round_limit: 3,
  negotiation_rounds_used: 0,
  tailor_profiles: {
    id: tailorProfileId,
    business_name: 'Abeni Atelier',
    display_name: 'Abeni Atelier',
    location: 'Lagos',
    avatar_url: null,
  },
  customer_profiles: {
    id: customerId,
    display_name: 'Amara Okafor',
    avatar_url: null,
  },
}

const previewTailorProfile = {
  id: tailorProfileId,
  user_id: tailorUserId,
  display_name: 'Abeni Atelier',
  business_name: 'Abeni Atelier',
  currency: 'NGN',
  consultation_call_type: 'VIDEO',
  is_live: true,
  is_verified: true,
} as TailorProfile

export const previewMessagesData: MessagesRenderData = {
  ...emptyMessagesSurfaceData,
  userId: customerId,
  orders: [previewOrder],
  messages: [
    {
      id: 'preview-message-1',
      order_id: previewOrder.id,
      sender_id: customerId,
      sender_role: 'CUSTOMER',
      sender_name: 'Amara',
      type: 'TEXT',
      body: 'Hi! I love the progress. Could we keep the jacket slightly cropped?',
      photo_url: null,
      voice_url: null,
      read_at: '2026-09-22T15:25:00.000Z',
      created_at: '2026-09-22T15:20:00.000Z',
    },
    {
      id: 'preview-message-2',
      order_id: previewOrder.id,
      sender_id: tailorUserId,
      sender_role: 'TAILOR',
      sender_name: 'Abeni Atelier',
      type: 'TEXT',
      body: 'Absolutely — I will keep the proportion from your reference and share another update tomorrow.',
      photo_url: null,
      voice_url: null,
      read_at: '2026-09-22T15:30:00.000Z',
      created_at: '2026-09-22T15:28:00.000Z',
    },
  ],
}

export const previewTailorOrderData: OrderDetailRenderData = {
  ...emptyOrderDetailSurfaceData,
  order: previewOrder,
  userId: tailorUserId,
  tailorProfile: previewTailorProfile,
  customerProfile: null,
  stageUpdates: [
    {
      id: 'preview-stage-update',
      order_id: previewOrder.id,
      stage: 'SEWING',
      note: 'Main construction is underway.',
      photo_url: null,
      created_at: '2026-09-22T14:00:00.000Z',
    },
  ],
}

export const previewCustomerOrderData: OrderDetailRenderData = {
  ...emptyOrderDetailSurfaceData,
  order: previewOrder,
  userId: customerId,
  tailorProfile: null,
  customerProfile: {
    user_id: customerId,
    display_name: 'Amara Okafor',
    avatar_url: null,
    measurements: { bust: 92, waist: 74, hips: 101 },
    unit_preference: 'CM',
    updated_at: '2026-09-22T12:00:00.000Z',
  } as CustomerProfile,
}

const previewReadyPayoutProfile = {
  ...previewTailorProfile,
  profile_completed: true,
  id_verification_status: 'VERIFIED',
  supports_ready_made: true,
  currency: 'USD',
  payout_currency: 'USD',
  payout_provider: 'STRIPE',
  payout_account_type: 'STRIPE_CONNECT',
  payout_account_verified: true,
  payout_reverification_required: false,
  payout_bank_name: 'Preview Bank',
  payout_account_name: 'Abeni Atelier',
  payout_account_masked: '•••• 4242',
  payout_country_code: 'US',
  manual_bank_entry: false,
  manual_bank_name: null,
  manual_bank_account_name: null,
  manual_bank_verification_status: null,
  paystack_recipient_code: null,
  stripe_connect_account_id: 'acct_preview',
} as TailorProfile

export const previewPayoutData: PayoutRenderData = {
  tailorProfile: previewReadyPayoutProfile,
}

export const previewEarningsData: EarningsRenderData = {
  tailorProfile: previewReadyPayoutProfile,
  orders: [
    {
      ...previewOrder,
      id: 'preview-paid-order',
      reference: 'DRP-PAID-1041',
      stage: 'COMPLETE',
      escrow_released: true,
      currency: 'USD',
      quoted_currency: 'USD',
      subtotal_amount: 145000,
      total_amount: 158000,
      platform_fee_amount: 13000,
      tax_amount: 0,
    },
    {
      ...previewOrder,
      id: 'preview-pending-order',
      reference: 'DRP-PENDING-1042',
      stage: 'SEWING',
      currency: 'USD',
      quoted_currency: 'USD',
      subtotal_amount: 185000,
      total_amount: 198000,
      platform_fee_amount: 13000,
      tax_amount: 0,
    },
  ],
  payouts: [
    {
      id: 'preview-payout',
      tailor_profile_id: tailorProfileId,
      amount: 145000,
      currency: 'USD',
      provider: 'STRIPE',
      status: 'PAID',
      payout_purpose: 'ORDER_EARNING',
      provider_payout_id: 'po_preview',
      provider_transfer_status: 'AVAILABLE_IN_PROVIDER_BALANCE',
      bank_settlement_status: 'PAID',
      provider_bank_payout_id: 'po_bank_preview',
      bank_settlement_expected_at: null,
      bank_settlement_completed_at: '2026-09-22T12:00:00.000Z',
      bank_settlement_failure_code: null,
      blocked_reason: null,
      order_id: 'preview-paid-order',
      initiated_at: '2026-09-21T12:00:00.000Z',
      completed_at: '2026-09-22T12:00:00.000Z',
      failed_at: null,
      processed_at: '2026-09-22T12:00:00.000Z',
    },
  ],
  bankActivity: [],
  warning: null,
}

export const previewShopData: ShopRenderData = {
  userId: tailorUserId,
  tailorProfile: previewReadyPayoutProfile,
  pickupDetails: null,
  warning: null,
  exploreItems: [],
  sellerItems: [
    {
      id: 'preview-shop-item',
      tailor_profile_id: tailorProfileId,
      title: 'Emerald occasion set',
      description: 'A structured jacket and wide-leg trouser set made to order.',
      category: 'Sets',
      sizes: ['S', 'M', 'L'],
      size_inventory: { S: 1, M: 2, L: 1 },
      price_amount: 185000,
      currency: 'NGN',
      photo_urls: null,
      stock_status: 'IN_STOCK',
      inventory_quantity: 4,
      size_guide: null,
      is_live: true,
      pickup_available: false,
      delivery_available: true,
      shipping_available: true,
      updated_at: '2026-09-22T12:00:00.000Z',
      tailor_profiles: {
        id: tailorProfileId,
        business_name: 'Abeni Atelier',
        display_name: 'Abeni Atelier',
        avatar_url: null,
      },
    },
  ],
}

export const previewVerifiedIdentityProfile = {
  ...previewReadyPayoutProfile,
  id_verification_status: 'VERIFIED',
  is_verified: true,
  is_live: true,
} as TailorProfile

export const previewRejectedIdentityProfile = {
  ...previewReadyPayoutProfile,
  id_verification_status: 'REJECTED',
  is_verified: false,
  is_live: false,
  id_verification_rejection_reason: 'Replace the public profile image before resubmitting.',
  id_verification_metadata: { rejection_code: 'INVALID_PROFILE_IMAGE' },
} as TailorProfile

export const previewPortfolioData: ProfileRenderData = {
  userId: tailorUserId,
  tailorProfile: {
    ...previewVerifiedIdentityProfile,
    portfolio_video_urls: [],
    availability: 'OPEN',
    price_range_min: 85000,
    price_range_max: 280000,
  },
  pickupDetails: null,
  sellerItems: [],
  warning: null,
  portfolioItems: [
    {
      id: 'preview-portfolio-1',
      image_url: 'http://127.0.0.1:3004/editorial/drapeon-craft-hero-v1.jpg',
      title: 'Emerald evening set',
      description: 'Structured occasion tailoring with hand-finished details.',
      category: 'Occasion wear',
      sort_order: 0,
      created_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'preview-portfolio-2',
      image_url: 'http://127.0.0.1:3004/editorial/drapeon-finishing-detail-v1.jpg',
      title: 'Hand-finished detail',
      description: 'Close-up of the finishing and construction.',
      category: 'Details',
      sort_order: 1,
      created_at: '2026-09-21T12:00:00.000Z',
    },
  ],
  portfolioMedia: [
    {
      id: 'preview-portfolio-media-1',
      kind: 'IMAGE',
      url: '/editorial/drapeon-craft-hero-v1.jpg',
      posterUrl: null,
      width: 1600,
      height: 1200,
      focalX: 0.5,
      focalY: 0.45,
      altText: 'Emerald tailored evening set displayed in the atelier',
      isPrimary: true,
      position: 0,
    },
    {
      id: 'preview-portfolio-media-2',
      kind: 'IMAGE',
      url: '/editorial/drapeon-finishing-detail-v1.jpg',
      posterUrl: null,
      width: 1600,
      height: 1200,
      focalX: 0.5,
      focalY: 0.5,
      altText: 'Close-up of hand-finished garment construction',
      isPrimary: false,
      position: 1,
    },
  ],
}

export const previewSellingSetupData: ProfileRenderData = {
  ...previewPortfolioData,
  userId: null,
  tailorProfile: {
    ...previewVerifiedIdentityProfile,
    profile_completed: false,
    display_name: 'Abeni Atelier',
    business_name: 'Abeni Atelier',
    location: 'Lagos, Nigeria',
    bio: 'Contemporary occasion wear and structured tailoring, made with careful fittings and hand-finished details.',
    languages: ['English', 'Yoruba'],
    specialty_tags: ['Occasion wear', 'Two-piece sets'],
    currency: 'NGN',
    price_range_min: 85000,
    price_range_max: 280000,
    availability: 'OPEN',
    seller_type: 'TAILOR_SHOP',
    supports_custom_orders: true,
    supports_ready_made: true,
    accepts_custom_orders_now: true,
    shop_paused: false,
    pickup_available: false,
    delivery_available: true,
    shipping_available: true,
    consultation_mode: 'FREE',
    consultation_requirement: 'OPTIONAL',
    consultation_duration_minutes: 30,
    consultation_call_type: 'VIDEO',
    consultation_fee_creditable: false,
  },
}

export const previewMaterialAdvanceData = {
  userId: customerId,
  materialAdvances: [
    {
      id: 'preview-material-advance',
      order_id: previewOrder.id,
      customer_id: customerId,
      tailor_id: tailorUserId,
      requested_by: tailorUserId,
      title: 'Aso-oke fabric deposit',
      description: 'Supplier deposit for the approved emerald Aso-oke and matching lining.',
      amount: 45000,
      currency: 'NGN',
      status: 'REQUESTED',
      release_status: 'PENDING',
      estimate_storage_bucket: 'commercial-evidence',
      estimate_storage_path: 'preview/material-estimate.jpg',
      funding_source: 'LEGACY_SEPARATE_PAYMENT',
      created_at: '2026-09-22T12:00:00.000Z',
      updated_at: '2026-09-22T12:00:00.000Z',
    } as MaterialAdvance,
  ],
}

export const previewDispatchState: AccountDispatchState = {
  ok: true,
  role: 'CUSTOMER',
  paymentConfirmed: false,
  currentMethod: 'LOCAL_DELIVERY',
  canRequestDelivery: true,
  deliveryDetails: {
    recipientName: 'Amara Okafor',
    recipientPhone: '+2348012345678',
    address: '12 Admiralty Way, Lekki Phase 1, Lagos',
    city: 'Lagos',
    region: 'Lagos',
    postalCode: '106104',
    countryCode: 'NG',
  },
  run: {
    id: 'preview-dispatch-run',
    order_id: previewOrder.id,
    method: 'LOCAL_DELIVERY',
    status: 'AWAITING_CUSTOMER_DECISION',
    funding_status: 'SHORTFALL_REQUIRED',
    currency: 'NGN',
    captured_allowance_amount: 10000,
    actual_provider_cost_amount: 15000,
    shortfall_subtotal_amount: 5000,
    shortfall_tax_amount: 0,
    shortfall_fee_amount: 0,
    shortfall_total_amount: 5000,
    customer_refund_amount: 0,
    customer_refund_tax_amount: 0,
    subsidy_restored_amount: 0,
    provider_name: 'Drapeon Local Delivery',
    provider_quote_evidence: [],
  },
  parcels: [
    {
      id: 'preview-parcel',
      status: 'QUOTE_READY',
      provider_name: 'Drapeon Local Delivery',
      tracking_number: null,
      tracking_url: null,
      eta_at: '2026-09-25T17:00:00.000Z',
      last_location: { label: 'Lekki, Lagos' },
    },
  ],
  events: [
    {
      id: 'preview-dispatch-event',
      event_type: 'QUOTE_RECORDED',
      customer_note: 'Provider price confirmed for local delivery.',
      occurred_at: '2026-09-23T14:00:00.000Z',
      evidence_media: [],
    },
  ],
}
