import { Colors, Fonts, FontSize, FontWeight, Radius, Shadow, Spacing } from '@/constants/theme'
import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bone },
  stateWrap: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: Spacing.xl },
  stateCard: {
    width: '100%',
    maxWidth: 440,
    backgroundColor: Colors.white,
    borderRadius: Radius.xl,
    padding: Spacing.xl,
    gap: Spacing.lg,
    alignItems: 'center',
    ...Shadow.lg,
  },
  stateEyebrow: {
    fontSize: FontSize.xs,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  stateTitle: {
    fontSize: FontSize.lg,
    color: Colors.ink,
    fontWeight: FontWeight.bold,
    textAlign: 'center',
  },
  stateHint: { fontSize: FontSize.sm, color: Colors.inkLight, textAlign: 'center', lineHeight: 21 },
  back: { paddingHorizontal: Spacing.xl, paddingTop: Spacing.md, paddingBottom: Spacing.sm },
  backText: { color: Colors.needleGreenDark, fontSize: FontSize.md, fontWeight: FontWeight.medium },
  scroll: { flex: 1 },
  content: { padding: Spacing.xl, gap: Spacing.md },

  heading: {
    fontSize: FontSize.xxl,
    fontWeight: FontWeight.bold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  subheading: { fontSize: FontSize.sm, color: Colors.midGrey, marginTop: 4 },
  stageRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, marginTop: Spacing.sm },
  amount: { fontSize: FontSize.sm, fontWeight: FontWeight.semibold, color: Colors.ink },
  messageAction: {
    minHeight: 48,
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: 11,
    borderRadius: Radius.md,
    backgroundColor: Colors.needleGreenLight,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '30',
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  messageActionText: {
    flex: 1,
    fontSize: FontSize.md,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.semibold,
  },
  orderTypePill: {
    marginTop: Spacing.sm,
    alignSelf: 'flex-start',
    backgroundColor: Colors.needleGreenLight,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
  },
  orderTypePillText: {
    fontSize: FontSize.xs,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  alertCard: {
    backgroundColor: Colors.needleGreenLight,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '40',
  },
  alertTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  alertSub: { fontSize: FontSize.sm, color: Colors.inkLight, lineHeight: 20 },
  compactActionMenuButton: {
    minHeight: 48,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
  },
  compactActionMenuText: {
    fontSize: FontSize.sm,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.semibold,
  },

  stageCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.md,
    padding: 14,
    gap: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.lightGrey,
  },
  stageCardTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  stageCardSub: { fontSize: 13, color: Colors.inkLight, lineHeight: 19 },
  stageCardHint: { fontSize: 12, color: Colors.midGrey, lineHeight: 18 },

  consultationCard: { borderColor: Colors.kanteRust + '60', borderWidth: 1.5 },
  consultationInfo: {
    backgroundColor: Colors.boneDeep,
    borderRadius: Radius.md,
    padding: Spacing.md,
  },
  consultationInfoText: { fontSize: FontSize.sm, color: Colors.inkLight, lineHeight: 20 },

  // Body profile
  bodyCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    gap: Spacing.md,
    ...Shadow.sm,
    borderWidth: 1,
    borderColor: Colors.kanteRust + '55',
  },
  bodyCardTitle: { fontSize: FontSize.md, fontWeight: FontWeight.semibold, color: Colors.ink },
  bodyCardRow: { gap: Spacing.sm },
  fitFlagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs },
  fitFlagBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    backgroundColor: Colors.kanteRustLight,
    borderRadius: Radius.full,
  },
  fitFlagText: { fontSize: FontSize.xs, color: Colors.kanteRust, fontWeight: FontWeight.semibold },
  bodyNote: {
    backgroundColor: Colors.bone,
    borderRadius: Radius.sm,
    padding: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.kanteRust + '35',
  },
  bodyNoteText: { fontSize: FontSize.sm, color: Colors.inkLight, fontStyle: 'italic' },

  section: { gap: Spacing.sm },
  sectionTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  fitStyleTag: { color: Colors.midGrey, fontWeight: FontWeight.regular },

  briefText: { fontSize: FontSize.md, color: Colors.inkLight, lineHeight: 24 },
  briefMeta: { gap: Spacing.sm },
  briefRow: { flexDirection: 'row', justifyContent: 'space-between', gap: Spacing.md },
  briefRowLabel: { fontSize: FontSize.sm, color: Colors.midGrey },
  briefRowValue: {
    flex: 1,
    textAlign: 'right',
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
    color: Colors.ink,
  },
  dossierList: { gap: Spacing.sm },
  sheetSectionStack: { gap: Spacing.md },
  stageChoiceList: { gap: Spacing.sm },
  quoteRevisionReasonRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs },
  dossierRowStacked: { gap: 6 },
  dossierRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  dossierStackedText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
    color: Colors.ink,
    lineHeight: 20,
  },
  dossierLinkText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
    color: Colors.needleGreenDark,
    lineHeight: 20,
  },
  dossierMediaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs },
  dossierMediaTile: {
    width: '31%',
    aspectRatio: 1,
    borderRadius: Radius.md,
    overflow: 'hidden',
    backgroundColor: Colors.boneDeep,
  },
  dossierMediaImage: { width: '100%', height: '100%' },
  supportCard: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    paddingVertical: 12,
    paddingHorizontal: 0,
    gap: 8,
    borderWidth: 0,
    borderBottomWidth: 1,
    borderColor: Colors.midGrey + '55',
  },
  disclosureCard: {
    paddingHorizontal: Spacing.sm,
    backgroundColor: Colors.boneDeep,
  },
  supportCardWarning: {
    borderWidth: 1,
    borderColor: Colors.kanteRust + '40',
  },
  supportCardSuccess: {
    borderWidth: 1,
    borderColor: Colors.needleGreen + '40',
    backgroundColor: Colors.needleGreenLight,
  },
  referralTrustCard: {
    flexDirection: 'row',
    gap: Spacing.sm,
    alignItems: 'flex-start',
    backgroundColor: Colors.needleGreenLight,
    borderRadius: Radius.md,
    padding: Spacing.sm,
  },
  referralTrustTitle: {
    fontSize: FontSize.sm,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.semibold,
  },
  referralTrustText: {
    marginTop: 2,
    fontSize: FontSize.xs,
    color: Colors.inkLight,
    lineHeight: 18,
  },
  supportCardTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  quoteCoverageChip: {
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    borderRadius: Radius.full,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: Colors.white,
  },
  quoteCoverageChipSelected: {
    borderColor: Colors.needleGreen,
    backgroundColor: Colors.needleGreenLight,
  },
  quoteCoverageText: {
    color: Colors.inkLight,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
  },
  quoteCoverageTextSelected: { color: Colors.needleGreenDark, fontWeight: FontWeight.semibold },
  quoteReviewRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    borderRadius: Radius.md,
    backgroundColor: Colors.white,
    padding: Spacing.md,
  },
  quoteReviewRowChecked: {
    borderColor: Colors.needleGreen,
    backgroundColor: Colors.needleGreenLight,
  },
  quoteReviewCheck: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: Colors.midGrey,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  quoteReviewCheckChecked: { borderColor: Colors.needleGreen, backgroundColor: Colors.needleGreen },
  quoteReviewCopy: {
    flex: 1,
    color: Colors.ink,
    fontSize: FontSize.sm,
    lineHeight: 21,
    fontFamily: Fonts.bodyMedium,
  },
  quoteTotalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
    paddingTop: Spacing.xs,
  },
  quoteDraftStatus: {
    alignSelf: 'flex-end',
    fontSize: FontSize.xs,
    color: Colors.inkLight,
    fontWeight: FontWeight.medium,
  },
  quoteTotalValue: { color: Colors.ink, fontSize: FontSize.lg, fontWeight: FontWeight.bold },
  disclosureHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  disclosureCopy: {
    flex: 1,
    gap: 3,
  },
  disclosureSummary: {
    fontSize: FontSize.xs,
    color: Colors.midGrey,
    lineHeight: 18,
  },
  disclosureBody: {
    paddingTop: Spacing.xs,
    gap: 6,
  },
  disclosureSection: {
    gap: 6,
  },
  disclosureSectionBordered: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Colors.lightGrey,
    paddingTop: Spacing.md,
    marginTop: Spacing.xs,
  },
  supportMetaList: { gap: 6 },
  advanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    backgroundColor: Colors.bone,
  },
  advanceEvidenceActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  advanceTitle: { fontSize: FontSize.sm, color: Colors.ink, fontWeight: FontWeight.semibold },
  supportBadge: {
    alignSelf: 'flex-start',
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
  },
  supportBadgeWarning: { backgroundColor: Colors.kanteRustLight },
  supportBadgeSuccess: { backgroundColor: Colors.needleGreenLight },
  supportBadgeText: { fontSize: FontSize.xs, fontWeight: FontWeight.semibold },
  supportBadgeTextWarning: { color: Colors.kanteRust },
  supportBadgeTextSuccess: { color: Colors.needleGreenDark },
  supportBodyText: { fontSize: 13, color: Colors.inkLight, lineHeight: 19 },
  supportHint: { fontSize: 12, color: Colors.midGrey, lineHeight: 18 },
  inlineLink: {
    alignSelf: 'flex-start',
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.needleGreenDark,
    textDecorationLine: 'underline',
  },
  fabricChangeFeedbackLink: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '45',
    backgroundColor: Colors.needleGreenLight,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
  },
  fabricChangeFeedbackLinkText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    color: Colors.needleGreenDark,
  },
  fabricChangeFeedbackSheet: { gap: Spacing.lg },
  fabricChangeFeedbackBody: {
    fontSize: FontSize.md,
    color: Colors.ink,
    lineHeight: 24,
  },
  fabricDecisionSuccess: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '45',
    borderRadius: Radius.md,
    backgroundColor: Colors.needleGreenLight,
    padding: Spacing.sm,
  },
  fabricDecisionSuccessIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.needleGreen,
  },
  fabricDecisionSuccessCopy: { flex: 1, gap: 2 },
  fabricDecisionSuccessTitle: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.needleGreenDark,
  },
  fabricDecisionSuccessBody: {
    fontSize: FontSize.xs,
    lineHeight: 18,
    color: Colors.inkLight,
  },
  timeline: { gap: 0, paddingTop: Spacing.xs },
  timelineItem: { flexDirection: 'row', gap: 10, paddingBottom: 12 },
  timelineDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    marginTop: 5,
    backgroundColor: Colors.needleGreen,
  },
  timelineContent: { flex: 1, gap: 3 },
  timelineStage: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  timelineNote: { fontSize: 12, color: Colors.inkLight, fontStyle: 'italic', lineHeight: 18 },
  timelinePhoto: {
    width: '100%',
    height: 176,
    borderRadius: Radius.md,
    backgroundColor: Colors.boneDeep,
    marginTop: Spacing.xs,
    overflow: 'hidden',
  },
  timelineDate: { fontSize: 10, color: Colors.midGrey },
  measurementConfirmFieldWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs },
  measurementConfirmFieldChip: {
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.kanteRust + '40',
  },
  measurementConfirmFieldText: {
    fontSize: FontSize.xs,
    color: Colors.kanteRust,
    fontWeight: FontWeight.semibold,
  },
  styleChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  styleChip: {
    borderRadius: Radius.full,
    backgroundColor: Colors.needleGreenLight,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
  },
  styleChipText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    color: Colors.needleGreenDark,
  },
  referenceLinkList: { gap: 6 },
  referenceLinkRow: {
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.bone,
    padding: Spacing.sm,
    gap: 2,
  },
  referenceLinkHost: { fontSize: FontSize.xs, fontWeight: FontWeight.semibold, color: Colors.ink },
  referenceLinkText: { fontSize: FontSize.xs, color: Colors.needleGreenDark },
  handoffIssueCard: {
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.lg,
    backgroundColor: Colors.bone,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
  },
  handoffIssueHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  handoffIssueTitle: {
    flex: 1,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
  },
  handoffStatusPill: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: Radius.full,
    backgroundColor: Colors.needleGreenLight,
  },
  handoffStatusPillEscalated: {
    backgroundColor: Colors.accentLight,
  },
  handoffStatusText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    color: Colors.needleGreenDark,
  },
  supportWarningCard: {
    backgroundColor: Colors.kanteRustLight,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    gap: Spacing.xs,
  },
  supportWarningTitle: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.kanteRust,
  },
  supportWarningText: { fontSize: FontSize.sm, color: Colors.inkLight, lineHeight: 20 },

  fitNote: {
    backgroundColor: Colors.needleGreenLight,
    borderRadius: Radius.md,
    padding: Spacing.md,
    gap: 4,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '35',
  },
  fitNoteLabel: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    color: Colors.needleGreenDark,
  },
  fitNoteText: { fontSize: FontSize.sm, color: Colors.inkLight, fontStyle: 'italic' },

  refPhoto: { width: 152, height: 152, borderRadius: Radius.md, backgroundColor: Colors.boneDeep },

  measureGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  measureItem: {
    width: '47%',
    backgroundColor: Colors.white,
    borderRadius: Radius.sm,
    padding: Spacing.md,
    gap: 2,
  },
  measureLabel: { fontSize: FontSize.xs, color: Colors.midGrey },
  measureValue: { fontSize: FontSize.sm, fontWeight: FontWeight.semibold, color: Colors.ink },
  additionalMeasureBlock: { gap: Spacing.sm, marginTop: Spacing.md },
  additionalMeasureTitle: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },

  messageCta: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: Colors.lightGrey,
    ...Shadow.lg,
  },

  backLink: { color: Colors.needleGreenDark, fontSize: FontSize.md, fontWeight: FontWeight.medium },
  retryBtn: {
    backgroundColor: Colors.needleGreen,
    borderRadius: Radius.full,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.xxxl,
  },
  retryBtnText: {
    color: Colors.textInverse,
    fontWeight: FontWeight.semibold,
    fontSize: FontSize.sm,
  },
  secondaryBtn: {
    backgroundColor: Colors.white,
    borderColor: Colors.lightGrey,
    borderRadius: Radius.full,
    borderWidth: 1,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.xxxl,
  },
  secondaryBtnText: { color: Colors.ink, fontWeight: FontWeight.semibold, fontSize: FontSize.sm },

  // Modal shared
  modalSafe: { flex: 1, backgroundColor: Colors.bone },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: Colors.lightGrey,
    backgroundColor: Colors.white,
  },
  modalClose: {
    color: Colors.needleGreenDark,
    fontSize: FontSize.md,
    fontWeight: FontWeight.medium,
    width: 60,
  },
  modalTitle: { fontSize: FontSize.lg, fontWeight: FontWeight.semibold, color: Colors.ink },
  modalScroll: { flex: 1 },
  modalContent: { padding: Spacing.xl, gap: Spacing.xl, paddingBottom: Spacing.xxxl },
  quoteModalContent: { paddingBottom: 136 },
  quoteActionDockPrimary: { flex: 1 },
  modalFooter: {
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.lightGrey,
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.xl,
  },
  modalFooterGuidance: {
    color: Colors.inkLight,
    fontSize: FontSize.xs,
    lineHeight: 18,
    marginBottom: Spacing.sm,
    textAlign: 'center',
  },
  modalSectionLabel: { fontSize: FontSize.sm, fontWeight: FontWeight.semibold, color: Colors.ink },
  modalHelpText: { fontSize: FontSize.xs, color: Colors.midGrey, lineHeight: 18 },
  measurementFieldPicker: { gap: Spacing.sm },
  choiceList: { gap: Spacing.sm },
  consultationTermsHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  consultationTermsCopy: { flex: 1, gap: 3 },
  consultationPolicyEditor: { gap: Spacing.lg, paddingTop: Spacing.sm },
  consultationOptionGroup: { gap: Spacing.sm },
  consultationChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  consultationChip: {
    minHeight: 42,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    borderRadius: Radius.full,
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  consultationChipActive: {
    borderColor: Colors.needleGreen,
    backgroundColor: Colors.needleGreenLight,
  },
  consultationChipText: {
    fontSize: FontSize.sm,
    color: Colors.inkLight,
    fontWeight: FontWeight.medium,
  },
  consultationChipTextActive: { color: Colors.needleGreenDark, fontWeight: FontWeight.semibold },
  consultationCreditRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    minHeight: 44,
  },
  consultationCheck: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: Colors.midGrey,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  consultationCheckActive: { borderColor: Colors.needleGreen, backgroundColor: Colors.needleGreen },
  consultationCreditText: { flex: 1, fontSize: FontSize.sm, lineHeight: 20, color: Colors.ink },
  consultationEditorActions: { gap: Spacing.sm },
  consultationSavedRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  consultationSavedText: {
    fontSize: FontSize.xs,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.medium,
  },
  fieldError: { fontSize: FontSize.xs, color: Colors.error, lineHeight: 18 },
  selectableSettingRow: {
    minHeight: 52,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  selectableSettingRowActive: {
    borderColor: Colors.needleGreen,
    backgroundColor: Colors.needleGreenLight,
  },
  selectableSettingRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectableSettingRadioActive: {
    borderColor: Colors.needleGreen,
    backgroundColor: Colors.needleGreen,
  },
  selectableSettingBody: { flex: 1 },
  selectableSettingLabel: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
  },
  selectableSettingLabelActive: { color: Colors.needleGreenDark },
  selectableSettingDetail: {
    marginTop: 3,
    fontSize: FontSize.xs,
    lineHeight: 17,
    color: Colors.midGrey,
  },
  policySummaryRow: {
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
  },
  policySummaryLabel: { fontSize: FontSize.xs, color: Colors.midGrey, marginBottom: 3 },
  policySummaryValue: { fontSize: FontSize.sm, color: Colors.ink, fontWeight: FontWeight.semibold },
  shippingFields: { gap: Spacing.sm },
  shippingWarning: {
    fontSize: FontSize.sm,
    lineHeight: 20,
    color: Colors.error,
  },

  nextStageRow: {
    backgroundColor: Colors.needleGreenLight,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    gap: 4,
  },
  nextStageLabel: { fontSize: FontSize.sm, color: Colors.inkLight },
  nextStageValue: {
    fontSize: 20,
    fontWeight: FontWeight.bold,
    color: Colors.needleGreenDark,
    fontFamily: Fonts.display,
  },

  photoLabel: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    marginBottom: 4,
  },
  photoHint: {
    fontSize: FontSize.xs,
    color: Colors.midGrey,
    marginBottom: Spacing.md,
    lineHeight: 18,
  },
  photoPickBtn: {
    minHeight: 142,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: Colors.needleGreen + '55',
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.needleGreenLight,
    padding: Spacing.lg,
    gap: 6,
  },
  photoPickIcon: {
    width: 42,
    height: 42,
    borderRadius: Radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
  },
  photoPickText: {
    fontSize: FontSize.md,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.semibold,
  },
  photoPickSubtext: { fontSize: FontSize.xs, color: Colors.inkLight, textAlign: 'center' },
  photoPreviewWrap: { gap: Spacing.sm },
  photoPreview: {
    width: '100%',
    height: 200,
    borderRadius: Radius.md,
    backgroundColor: Colors.boneDeep,
  },
  photoActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  photoReplace: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '55',
    paddingHorizontal: Spacing.md,
  },
  photoReplaceText: {
    color: Colors.needleGreenDark,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
  },
  photoRemove: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.error + '44',
    paddingHorizontal: Spacing.md,
  },
  photoRemoveText: { color: Colors.error, fontSize: FontSize.sm, fontWeight: FontWeight.semibold },
  mediaSourceInline: {
    marginTop: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '44',
    borderRadius: Radius.lg,
    backgroundColor: Colors.bone,
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  mediaSourceInlineHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.sm },
  mediaSourceInlineClose: {
    width: 44,
    height: 44,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mediaSourceTitle: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.bold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  mediaSourceText: {
    fontSize: FontSize.sm,
    color: Colors.inkLight,
    lineHeight: 20,
  },
  mediaSourceAction: {
    minHeight: 64,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.bone,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  mediaSourceActionCopy: { flex: 1, gap: 2 },
  mediaSourceActionTitle: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
  },
  mediaSourceActionText: { fontSize: FontSize.xs, color: Colors.midGrey, lineHeight: 17 },

  // Collection code modal
  codeModalContent: { flex: 1, padding: Spacing.xl, gap: Spacing.xl, alignItems: 'center' },
  codeInstruction: {
    fontSize: FontSize.md,
    color: Colors.inkLight,
    textAlign: 'center',
    lineHeight: 22,
  },
  codeInputRow: { flexDirection: 'row', gap: Spacing.lg },
  codeInput: {
    width: 64,
    height: 80,
    borderRadius: Radius.md,
    backgroundColor: Colors.white,
    borderWidth: 2,
    borderColor: Colors.lightGrey,
    fontSize: 32,
    fontWeight: FontWeight.bold,
    color: Colors.ink,
    textAlign: 'center',
    ...Shadow.sm,
  },
  codeInputFilled: { borderColor: Colors.needleGreen },
  codeError: { fontSize: FontSize.sm, color: Colors.error, textAlign: 'center' },
  amountNote: { fontSize: FontSize.sm, color: Colors.midGrey, textAlign: 'center' },

  // Quote and consultation modal chips
  fieldLabel: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    marginBottom: Spacing.sm,
  },
  required: { color: Colors.error },
  reasonList: { gap: Spacing.sm },
  reasonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
  },
  reasonRowActive: {
    borderColor: Colors.needleGreen,
    backgroundColor: Colors.needleGreenLight,
  },
  reasonRadio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
  },
  reasonRadioActive: {
    borderColor: Colors.needleGreen,
    backgroundColor: Colors.needleGreen,
  },
  reasonText: { flex: 1, fontSize: FontSize.sm, color: Colors.ink },
  reasonTextActive: { color: Colors.needleGreenDark, fontWeight: FontWeight.semibold },
})

export { styles }
