import { Colors, Fonts, FontSize, FontWeight, Radius, Shadow, Spacing } from '@/constants/theme'
import { StyleSheet } from 'react-native'

import { PORTFOLIO_MIN_MARKER_LEFT } from './TailorSetupLimits'

const styles = StyleSheet.create({
  primaryDockButton: { flex: 1 },
  safe: { flex: 1, backgroundColor: Colors.bone },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
  },
  headerSpacer: { width: 68 },
  stepCount: { fontSize: FontSize.sm, color: Colors.midGrey },
  setupToast: {
    marginHorizontal: Spacing.xl,
    marginBottom: Spacing.sm,
    borderRadius: Radius.lg,
    borderWidth: 1,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  setupToastSuccess: {
    backgroundColor: Colors.needleGreenLight,
    borderColor: Colors.needleGreen + '33',
  },
  setupToastError: {
    backgroundColor: Colors.errorLight,
    borderColor: Colors.kanteRust,
  },
  setupToastText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    lineHeight: 20,
    textAlign: 'center',
  },
  setupToastTextSuccess: { color: Colors.needleGreen },
  setupToastTextError: { color: Colors.kanteRust },
  otpOverlay: {
    flex: 1,
    justifyContent: 'center',
    padding: Spacing.xl,
  },
  otpScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(12, 12, 11, 0.38)',
  },
  otpCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.xl,
    padding: Spacing.lg,
    gap: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    ...Shadow.md,
  },
  otpHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  otpIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.needleGreenLight,
  },
  otpClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.bone,
  },
  otpTitle: {
    fontFamily: Fonts.display,
    fontSize: FontSize.xl,
    fontWeight: FontWeight.bold,
    color: Colors.ink,
  },
  otpBody: {
    fontSize: FontSize.md,
    color: Colors.inkLight,
    lineHeight: 22,
  },
  otpInput: {
    minHeight: 58,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    borderRadius: Radius.lg,
    paddingHorizontal: Spacing.lg,
    fontSize: 24,
    letterSpacing: 4,
    color: Colors.ink,
    fontFamily: Fonts.bodyBold,
    fontWeight: FontWeight.bold,
    textAlign: 'center',
    backgroundColor: Colors.white,
  },
  otpInputError: {
    borderColor: Colors.kanteRust,
  },
  otpError: {
    color: Colors.kanteRust,
    fontSize: FontSize.sm,
    lineHeight: 20,
  },
  otpActions: {
    gap: Spacing.sm,
  },

  scroll: { flex: 1 },
  content: { padding: Spacing.xl, gap: Spacing.xl },
  heroMeta: { gap: Spacing.sm },
  heroMetaCard: {
    backgroundColor: Colors.bone,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    gap: 4,
  },
  heroMetaLabel: {
    fontSize: FontSize.xs,
    color: Colors.midGrey,
    fontWeight: FontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  heroMetaValue: {
    fontSize: FontSize.sm,
    color: Colors.ink,
    lineHeight: 20,
    fontWeight: FontWeight.medium,
  },
  guideCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    gap: Spacing.xs,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    ...Shadow.sm,
  },
  guideTitle: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  guideText: { fontSize: FontSize.sm, color: Colors.inkLight, lineHeight: 20 },
  setupChecklistCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    padding: Spacing.md,
    gap: Spacing.xs,
    ...Shadow.sm,
  },
  setupChecklistHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.xs,
    paddingBottom: Spacing.xs,
  },
  setupChecklistTitle: {
    fontFamily: Fonts.display,
    fontSize: FontSize.lg,
    fontWeight: FontWeight.bold,
    color: Colors.ink,
  },
  setupChecklistMeta: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    color: Colors.needleGreen,
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  setupChecklistRow: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.lg,
    backgroundColor: Colors.white,
  },
  setupChecklistRowActive: { backgroundColor: Colors.needleGreenLight },
  setupChecklistRowDeferred: { opacity: 0.62 },
  setupChecklistMark: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.boneDeep,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
  },
  setupChecklistMarkDone: {
    backgroundColor: Colors.needleGreen,
    borderColor: Colors.needleGreen,
  },
  setupChecklistMarkDeferred: {
    backgroundColor: Colors.bone,
  },
  setupChecklistMarkText: {
    color: Colors.midGrey,
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
  },
  setupChecklistMarkTextDone: { color: Colors.textInverse },
  setupChecklistTextBlock: { flex: 1, gap: 2 },
  setupChecklistLabel: {
    fontSize: FontSize.sm,
    color: Colors.ink,
    fontWeight: FontWeight.semibold,
  },
  setupChecklistDetail: {
    fontSize: FontSize.xs,
    color: Colors.midGrey,
    lineHeight: 16,
  },
  setupChecklistState: {
    fontSize: FontSize.xs,
    color: Colors.kanteRust,
    fontWeight: FontWeight.semibold,
  },
  setupChecklistStateDone: { color: Colors.needleGreen },
  setupChecklistStateDeferred: { color: Colors.midGrey },
  setupChecklistFooter: {
    marginTop: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.md,
    backgroundColor: Colors.bone,
  },
  setupChecklistFooterText: {
    fontSize: FontSize.xs,
    color: Colors.inkLight,
    lineHeight: 17,
  },
  identityRejectedCard: {
    backgroundColor: Colors.errorLight,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.kanteRust,
    padding: Spacing.md,
    gap: Spacing.xs,
  },
  identityRejectedCardCompact: {
    backgroundColor: Colors.errorLight,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.kanteRust,
    padding: Spacing.md,
    gap: Spacing.xs,
  },
  identityRejectedTitle: {
    fontSize: FontSize.sm,
    color: Colors.kanteRust,
    fontWeight: FontWeight.bold,
  },
  identityRejectedText: {
    fontSize: FontSize.xs,
    color: Colors.kanteRust,
    lineHeight: 18,
  },
  identityRejectedAction: {
    alignSelf: 'flex-start',
    marginTop: Spacing.xs,
    borderRadius: Radius.full,
    backgroundColor: Colors.kanteRust,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  identityRejectedActionText: {
    color: Colors.white,
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
  },
  formCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.xl,
    padding: Spacing.xl,
  },

  fields: { gap: Spacing.xl },
  profilePhotoPicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1.5,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.bone,
    padding: Spacing.md,
  },
  profilePhotoPickerError: {
    borderColor: Colors.error,
    backgroundColor: Colors.errorLight,
  },
  profilePhotoPickerRejected: {
    borderColor: Colors.kanteRust,
    backgroundColor: Colors.errorLight,
  },
  profilePhotoPreview: {
    width: 68,
    height: 68,
    borderRadius: 34,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.needleGreenLight,
  },
  profilePhotoPreviewRejected: {
    borderWidth: 2,
    borderColor: Colors.kanteRust,
  },
  profilePhotoRejectedBadge: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.kanteRust,
    color: Colors.textInverse,
    textAlign: 'center',
    fontSize: 9,
    fontWeight: FontWeight.bold,
    paddingVertical: 2,
  },
  profilePhotoInitial: {
    color: Colors.needleGreen,
    fontSize: FontSize.xl,
    fontWeight: FontWeight.bold,
  },
  profilePhotoCopy: { flex: 1, gap: 4 },
  profilePhotoTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  profilePhotoHint: {
    fontSize: FontSize.xs,
    color: Colors.midGrey,
    lineHeight: 17,
  },
  profilePhotoHintRejected: {
    color: Colors.kanteRust,
  },
  profilePhotoAction: {
    fontSize: FontSize.sm,
    color: Colors.needleGreen,
    fontWeight: FontWeight.semibold,
  },
  fieldLabel: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    marginBottom: Spacing.sm,
  },
  fieldHint: {
    fontSize: FontSize.xs,
    color: Colors.midGrey,
    lineHeight: 18,
    marginBottom: Spacing.md,
  },
  helperError: {
    fontSize: FontSize.xs,
    color: Colors.kanteRust,
    lineHeight: 18,
    marginTop: Spacing.sm,
  },
  required: { color: Colors.error },
  helperList: {
    gap: Spacing.sm,
    marginTop: -Spacing.xs,
    marginBottom: Spacing.md,
  },
  helperListRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
  },
  helperBullet: {
    width: 6,
    height: 6,
    borderRadius: Radius.full,
    backgroundColor: Colors.needleGreen,
    marginTop: 6,
  },
  helperListText: {
    flex: 1,
    fontSize: FontSize.xs,
    color: Colors.inkLight,
    lineHeight: 18,
    fontWeight: FontWeight.medium,
  },
  quickRangeList: {
    gap: Spacing.sm,
    marginTop: Spacing.sm,
    marginBottom: Spacing.md,
  },
  quickRangeRow: {
    minHeight: 58,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  quickRangeTitle: {
    fontSize: FontSize.sm,
    color: Colors.ink,
    fontWeight: FontWeight.semibold,
  },
  quickRangeBody: {
    fontSize: FontSize.xs,
    color: Colors.midGrey,
    lineHeight: 17,
  },
  selectorCard: {
    minHeight: 96,
    borderRadius: Radius.lg,
    borderWidth: 1.5,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    padding: Spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  selectorCardWarning: {
    borderColor: Colors.kanteRust,
    backgroundColor: Colors.errorLight,
  },
  selectorCopy: { flex: 1, gap: 3 },
  selectorMeta: {
    fontSize: FontSize.xs,
    color: Colors.needleGreen,
    fontWeight: FontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  selectorMetaWarning: { color: Colors.kanteRust },
  selectorTitle: {
    fontFamily: Fonts.display,
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
  },
  selectorBody: {
    fontSize: FontSize.xs,
    color: Colors.midGrey,
    lineHeight: 18,
  },

  // Pricing
  priceRow: { flexDirection: 'row', gap: Spacing.md },
  priceInput: { flex: 1, marginBottom: 0 },
  priceError: { fontSize: FontSize.xs, color: Colors.error, marginTop: Spacing.xs },

  // Portfolio
  portfolioStatus: { gap: Spacing.xs },
  portfolioBar: {
    height: 4,
    backgroundColor: Colors.lightGrey,
    borderRadius: 2,
    position: 'relative',
  },
  portfolioBarFill: { height: '100%', backgroundColor: Colors.needleGreen, borderRadius: 2 },
  portfolioBarMinMarker: {
    position: 'absolute',
    left: PORTFOLIO_MIN_MARKER_LEFT,
    top: -2,
    width: 2,
    height: 8,
    backgroundColor: Colors.needleGreen,
    borderRadius: 1,
  },
  portfolioCount: { fontSize: FontSize.xs, color: Colors.midGrey },
  portfolioMediaStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '24',
    backgroundColor: Colors.needleGreenLight,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  portfolioMediaStatusText: {
    flex: 1,
    fontSize: FontSize.xs,
    lineHeight: 18,
    color: Colors.needleGreen,
    fontWeight: FontWeight.medium,
  },
  portfolioGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  portfolioThumb: {
    width: 100,
    height: 100,
    borderRadius: Radius.md,
    position: 'relative',
  },
  portfolioThumbDragging: {
    borderWidth: 2,
    borderColor: Colors.needleGreen,
  },
  portfolioThumbPress: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    borderRadius: Radius.md,
  },
  portfolioImg: { width: '100%', height: '100%' },
  videoThumb: {
    backgroundColor: Colors.ink,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  videoBadge: {
    position: 'absolute',
    left: 6,
    bottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: Radius.full,
    backgroundColor: Colors.ink,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  videoLabel: { fontSize: 10, color: Colors.textInverse, fontWeight: FontWeight.semibold },
  coverBadge: {
    position: 'absolute',
    left: 6,
    top: 6,
    borderRadius: Radius.full,
    backgroundColor: Colors.needleGreen,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  coverBadgeText: {
    fontSize: 10,
    color: Colors.textInverse,
    fontWeight: FontWeight.bold,
  },
  portfolioDragBadge: {
    position: 'absolute',
    left: 6,
    right: 6,
    bottom: 6,
    borderRadius: Radius.full,
    backgroundColor: Colors.ink + 'CC',
    paddingHorizontal: 7,
    paddingVertical: 4,
    alignItems: 'center',
  },
  portfolioDragBadgeText: {
    fontSize: 9,
    color: Colors.textInverse,
    fontWeight: FontWeight.bold,
  },
  portfolioRemove: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  portfolioRemoveText: { color: Colors.textInverse, fontSize: 11, fontWeight: FontWeight.bold },
  portfolioAdd: {
    width: 100,
    height: 100,
    borderRadius: Radius.md,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  portfolioAddIcon: { fontSize: 24, color: Colors.midGrey },
  portfolioAddLabel: { fontSize: FontSize.xs, color: Colors.midGrey },
  portfolioAddHint: { fontSize: 9, color: Colors.midGrey, textAlign: 'center' },
  portfolioPending: {
    borderStyle: 'solid',
    borderColor: Colors.needleGreen + '40',
    backgroundColor: Colors.needleGreenLight,
  },
  mediaManagerOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  mediaManagerScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.34)',
  },
  mediaManagerSheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: Radius.xl,
    borderTopRightRadius: Radius.xl,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
    gap: Spacing.md,
  },
  mediaManagerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  mediaManagerEyebrow: {
    fontSize: FontSize.xs,
    color: Colors.needleGreen,
    fontWeight: FontWeight.semibold,
    textTransform: 'uppercase',
  },
  mediaManagerTitle: {
    fontSize: FontSize.lg,
    color: Colors.ink,
    fontWeight: FontWeight.bold,
    fontFamily: Fonts.display,
  },
  mediaManagerPreview: {
    height: 320,
    borderRadius: Radius.lg,
    overflow: 'hidden',
    backgroundColor: Colors.ink,
  },
  mediaManagerPreviewMedia: {
    width: '100%',
    height: '100%',
  },
  mediaManagerCarouselPage: {
    height: '100%',
  },
  mediaManagerDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  mediaManagerDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.lightGrey,
  },
  mediaManagerDotActive: {
    width: 18,
    backgroundColor: Colors.needleGreen,
  },
  mediaManagerHint: {
    fontSize: FontSize.xs,
    lineHeight: 18,
    color: Colors.midGrey,
    textAlign: 'center',
  },
  mediaManagerActions: {
    gap: Spacing.sm,
  },
  mediaManagerActionRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  mediaManagerAction: {
    minHeight: 48,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
  },
  mediaManagerActionCompact: {
    flex: 1,
  },
  mediaManagerActionDisabled: {
    backgroundColor: Colors.bone,
    opacity: 0.72,
  },
  mediaManagerActionDestructive: {
    borderColor: Colors.kanteRust + '24',
    backgroundColor: Colors.kanteRustLight,
  },
  mediaManagerActionText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.needleGreen,
  },
  mediaManagerActionTextDisabled: {
    color: Colors.midGrey,
  },
  mediaManagerActionTextDestructive: {
    color: Colors.kanteRust,
  },

  // Availability
  availCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.md,
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    borderWidth: 1.5,
    borderColor: Colors.lightGrey,
    marginBottom: Spacing.md,
  },
  availCardActive: { borderColor: Colors.needleGreen, backgroundColor: Colors.needleGreenLight },
  availRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    marginTop: 2,
    borderWidth: 2,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
  },
  availRadioActive: { borderColor: Colors.needleGreen, backgroundColor: Colors.needleGreen },
  availLabel: { fontSize: FontSize.md, fontWeight: FontWeight.semibold, color: Colors.inkLight },
  availLabelActive: { color: Colors.needleGreen },
  availHint: { fontSize: FontSize.xs, color: Colors.midGrey, marginTop: 2 },
  choiceGroup: { gap: Spacing.sm },
  choiceCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    borderWidth: 1.5,
    borderColor: Colors.lightGrey,
    gap: 4,
  },
  choiceCardActive: { borderColor: Colors.needleGreen, backgroundColor: Colors.needleGreenLight },
  choiceTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.inkLight,
    fontFamily: Fonts.display,
  },
  choiceTitleActive: { color: Colors.needleGreen },
  choiceHint: { fontSize: FontSize.xs, color: Colors.midGrey, lineHeight: 18 },
  fulfillmentFeeBlock: { gap: Spacing.md, marginTop: Spacing.md },

  // ID verification
  idPickBtn: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    padding: Spacing.xl,
    alignItems: 'center',
    gap: Spacing.sm,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: Colors.lightGrey,
  },
  idPickBtnError: {
    borderColor: Colors.error,
    backgroundColor: Colors.errorLight,
  },
  idPickIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.needleGreenLight,
  },
  idPickLabel: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  idPickHint: { fontSize: FontSize.xs, color: Colors.midGrey },
  idPreviewWrap: { gap: Spacing.md },
  idPreview: {
    width: '100%',
    height: 200,
    borderRadius: Radius.md,
    backgroundColor: Colors.boneDeep,
  },
  idRemove: { fontSize: FontSize.sm, color: Colors.error },
  identityConsentRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    marginTop: Spacing.md,
    paddingVertical: Spacing.xs,
  },
  identityConsentBox: {
    width: 24,
    height: 24,
    borderRadius: Radius.sm,
    borderWidth: 1.5,
    borderColor: Colors.midGrey,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  identityConsentBoxChecked: {
    backgroundColor: Colors.needleGreen,
    borderColor: Colors.needleGreen,
  },
  identityConsentCopy: {
    flex: 1,
    color: Colors.inkLight,
    fontSize: FontSize.xs,
    lineHeight: 19,
  },
  identityPrivacyLink: {
    minHeight: 44,
    paddingVertical: Spacing.sm,
    color: Colors.needleGreen,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
  },
  idExistingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    padding: Spacing.md,
  },
  idExistingIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.needleGreenLight,
  },
  idExistingCopy: { flex: 1, gap: 2 },
  idExistingTitle: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
  },
  idExistingHint: { fontSize: FontSize.xs, color: Colors.inkLight, lineHeight: 18 },
  idExistingAction: {
    fontSize: FontSize.sm,
    color: Colors.needleGreen,
    fontWeight: FontWeight.semibold,
  },
  setupFooterLinks: {
    alignItems: 'center',
    gap: Spacing.sm,
    paddingTop: Spacing.lg,
  },

  infoBox: {
    backgroundColor: Colors.boneDeep,
    borderRadius: Radius.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '25',
  },
  infoText: { fontSize: FontSize.xs, color: Colors.inkLight, lineHeight: 18 },
  inlineActionButton: {
    alignSelf: 'flex-start',
    marginTop: Spacing.sm,
    borderRadius: Radius.full,
    backgroundColor: Colors.needleGreen,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  inlineActionText: {
    color: Colors.textInverse,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
  },
  currencyProviderNote: {
    marginTop: Spacing.sm,
    marginBottom: Spacing.md,
  },

  cta: {
    padding: Spacing.xl,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.lightGrey,
    gap: Spacing.sm,
  },
  ctaCompact: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.xs,
    gap: 0,
  },
  modeSwitchLink: {
    alignSelf: 'center',
    minHeight: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeSwitchText: {
    fontSize: FontSize.sm,
    color: Colors.needleGreen,
    fontWeight: FontWeight.semibold,
  },
  signOutLink: { alignSelf: 'center' },
  signOutText: { fontSize: FontSize.sm, color: Colors.error },
  deleteAccountText: { fontSize: FontSize.sm, color: Colors.error, fontWeight: FontWeight.medium },
  minNote: { fontSize: FontSize.xs, color: Colors.midGrey, textAlign: 'center' },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheetScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.34)',
  },
  sheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: Radius.xl,
    borderTopRightRadius: Radius.xl,
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.xxl,
    gap: Spacing.md,
    maxHeight: '78%',
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 72,
    height: 5,
    borderRadius: 3,
    backgroundColor: Colors.lightGrey,
    marginBottom: Spacing.xs,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  sheetTitle: {
    flex: 1,
    fontFamily: Fonts.display,
    fontSize: FontSize.xl,
    fontWeight: FontWeight.bold,
    color: Colors.ink,
  },
  sheetClose: {
    width: 44,
    height: 44,
    borderRadius: Radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.bone,
  },
  sheetCloseText: {
    fontSize: 26,
    lineHeight: 28,
    color: Colors.inkLight,
  },
  sheetBody: {
    fontSize: FontSize.sm,
    color: Colors.inkLight,
    lineHeight: 21,
  },
  sheetPrivacyCopy: {
    fontSize: FontSize.xs,
    color: Colors.inkLight,
    lineHeight: 19,
  },
  sheetChoicesScroll: {
    flexGrow: 0,
    flexShrink: 1,
  },
  sheetChoicesContent: {
    gap: Spacing.md,
    paddingBottom: Spacing.xs,
  },
  sheetOption: {
    minHeight: 72,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  sheetOptionDisabled: {
    opacity: 0.45,
  },
  sheetOptionText: { flex: 1, gap: 3 },
  sheetOptionTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
  },
  sheetOptionBody: {
    fontSize: FontSize.xs,
    color: Colors.midGrey,
    lineHeight: 17,
  },
  sheetOptionChevron: {
    fontSize: 26,
    color: Colors.needleGreen,
    fontWeight: FontWeight.semibold,
  },
  choiceSheetRow: {
    minHeight: 78,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    padding: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  choiceSheetRowSelected: {
    borderColor: Colors.needleGreen,
    backgroundColor: Colors.needleGreenLight,
  },
  choiceSheetMark: {
    width: 28,
    height: 28,
    borderRadius: Radius.full,
    borderWidth: 1.5,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceSheetMarkSelected: {
    borderColor: Colors.needleGreen,
    backgroundColor: Colors.needleGreen,
  },
  choiceSheetMarkText: {
    fontSize: FontSize.sm,
    color: Colors.midGrey,
    fontWeight: FontWeight.bold,
  },
  choiceSheetMarkTextSelected: { color: Colors.textInverse },
  choiceSheetText: { flex: 1, gap: 3 },
  choiceSheetTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
  },
  choiceSheetBody: {
    fontSize: FontSize.xs,
    color: Colors.midGrey,
    lineHeight: 17,
  },
  sheetDoneButton: {
    minHeight: 52,
    borderRadius: Radius.full,
    backgroundColor: Colors.needleGreen,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetDoneButtonText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.textInverse,
  },

  suggestionsBox: {
    backgroundColor: Colors.white,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    marginTop: 2,
    overflow: 'hidden',
    ...Shadow.sm,
  },
  suggestionRow: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.lightGrey,
  },
  suggestionRowLast: { borderBottomWidth: 0 },
  suggestionText: { fontSize: FontSize.sm, color: Colors.ink },
})

export { styles }
