export function hsvToHex(h:number,s:number,v:number){const f=(n:number)=>{const k=(n+h/60)%6;return Math.round(255*v*(1-s*Math.max(0,Math.min(k,4-k,1)))).toString(16).padStart(2,'0')};return '#'+f(5)+f(3)+f(1)}
export function hexToHsv(hex:string){const [r,g,b]=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=d===0?0:max===r?((g-b)/d)%6:max===g?(b-r)/d+2:(r-g)/d+4;return {h:(h*60+360)%360,s:max===0?0:d/max,v:max}}
export function mountColour(read:()=>string,write:(c:string)=>void){
 const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;const canvas=el<HTMLCanvasElement>('colourWheel'),ctx=canvas.getContext('2d')!;let preview=hexToHsv(read()),dragging=false;
 function paint(){const size=200,c=100,img=ctx.createImageData(size,size);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const dx=x-c,dy=y-c,s=Math.hypot(dx,dy)/96;if(s>1)continue;const h=(Math.atan2(dy,dx)*180/Math.PI+360)%360;const hex=hsvToHex(h,s,preview.v),i=(y*size+x)*4;[1,3,5].forEach((p,j)=>img.data[i+j]=parseInt(hex.slice(p,p+2),16));img.data[i+3]=255}ctx.putImageData(img,0,0);const a=preview.h*Math.PI/180;ctx.beginPath();ctx.arc(100+Math.cos(a)*preview.s*96,100+Math.sin(a)*preview.s*96,5,0,Math.PI*2);ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.strokeStyle='#233c34';ctx.lineWidth=1;ctx.stroke()}
 function point(e:PointerEvent){const b=canvas.getBoundingClientRect(),x=(e.clientX-b.left)/b.width*200-100,y=(e.clientY-b.top)/b.height*200-100;preview.h=(Math.atan2(y,x)*180/Math.PI+360)%360;preview.s=Math.min(1,Math.hypot(x,y)/96);paint()}
 canvas.onpointerdown=e=>{dragging=true;canvas.setPointerCapture(e.pointerId);point(e)};canvas.onpointermove=e=>{if(dragging)point(e)};canvas.onpointerup=e=>{if(!dragging)return;point(e);dragging=false;write(hsvToHex(preview.h,preview.s,preview.v))};canvas.onpointercancel=()=>{dragging=false;sync()};
 for(const [id,k,scale] of [['colourHue','h',1],['colourSaturation','s',100],['colourLightness','v',100]] as const){el<HTMLInputElement>(id).onchange=()=>{preview[k]=Number(el<HTMLInputElement>(id).value)/scale;write(hsvToHex(preview.h,preview.s,preview.v))}}
 let palette:string[]=[];try{const p:unknown=JSON.parse(localStorage.getItem('drapeon-studio-palette')||'[]');if(Array.isArray(p))palette=p.filter((v):v is string=>typeof v==='string'&&/^#[a-f\d]{6}$/i.test(v)).slice(0,12)}catch{}
 const showPalette=()=>{const host=el('savedPalette');host.replaceChildren();for(const c of palette){const b=document.createElement('button');b.className='swatch';b.style.background=c;b.setAttribute('aria-label',`Use saved colour ${c}`);b.onclick=()=>write(c);host.append(b)}};
 el('saveColour').onclick=()=>{palette=[read(),...palette.filter(c=>c!==read())].slice(0,12);showPalette();try{localStorage.setItem('drapeon-studio-palette',JSON.stringify(palette));el('hexError').textContent='Colour saved to your palette.'}catch{el('hexError').textContent='Palette available for this session; browser storage unavailable.'}};showPalette();
 function sync(){preview=hexToHsv(read());el<HTMLInputElement>('colourHue').value=String(Math.round(preview.h));el<HTMLInputElement>('colourSaturation').value=String(Math.round(preview.s*100));el<HTMLInputElement>('colourLightness').value=String(Math.round(preview.v*100));paint()}
 return sync;
}
