import {LAYERS,LABELS,FIELDS,PIVOTS,neutral,boundedPlacement,placementTransform,transformPlacementWithPointers,type LayerId,type Placement,type PlacementPoint} from './studio-placement-state'
import type {Look} from './studio-state'
type Hooks={read:()=>Look;commit:(fn:(s:Look)=>void)=>void;render:()=>void;select:(id:LayerId)=>void;stopDrawing:()=>void;status:(text:string)=>void}
export function mountPlacement(canvas:SVGSVGElement,h:Hooks){
 const get=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
 const panel=get('placementPanel'),toggle=get<HTMLButtonElement>('arrangeToggle');
 const touchMode=window.matchMedia('(pointer: coarse)').matches||window.innerWidth<=620;
 let enabled=false,touchSelected=false,selected:LayerId|null='main',emptyMessage='Choose a clothing piece on the model to arrange it.',gesture:null|{id:number;kind:string;start:DOMPoint;initial:Placement;current:Placement;key:LayerId}=null;
 const touchPoints=new Map<number,DOMPoint>();
 let touchGesture:null|{ids:number[];key:LayerId;initial:Placement;current:Placement;start:PlacementPoint[]}=null;
 const node=()=>selected?canvas.querySelector<SVGGElement>(`[data-layer="${selected}"]`):null;
 const point=(event:PointerEvent)=>new DOMPoint(event.clientX,event.clientY).matrixTransform(canvas.getScreenCTM()!.inverse());
 const current=()=>selected?h.read().placements[selected]||neutral():neutral();
 function frameBounds(target:SVGGElement){
  const targetCTM=target.getCTM(),points:DOMPoint[]=[];
  if(targetCTM)for(const hit of target.querySelectorAll<SVGGraphicsElement>('[data-art-hit="true"]')){const childCTM=hit.getCTM();if(!childCTM)continue;const box=hit.getBBox(),matrix=targetCTM.inverse().multiply(childCTM);for(const [x,y]of [[box.x,box.y],[box.x+box.width,box.y],[box.x,box.y+box.height],[box.x+box.width,box.y+box.height]])points.push(new DOMPoint(x,y).matrixTransform(matrix))}
  if(!points.length||points.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.y)))return target.getBBox();
  const xs=points.map(p=>p.x),ys=points.map(p=>p.y),x=Math.min(...xs),y=Math.min(...ys);return {x,y,width:Math.max(...xs)-x,height:Math.max(...ys)-y};
 }
 function frame(){canvas.querySelector('[data-placement-ui]')?.remove();const target=node();if((!enabled&&(!touchMode||!touchSelected))||!target||!target.getBBox)return;const box=frameBounds(target);if(!box.width&&!box.height)return;const ns='http://www.w3.org/2000/svg';const g=document.createElementNS(ns,'g');g.setAttribute('data-placement-ui','');g.setAttribute('transform',target.getAttribute('transform')||'');g.setAttribute('aria-hidden','true');g.style.pointerEvents='none';const locked=current().locked;
 const rect=document.createElementNS(ns,'rect');for(const [key,value]of Object.entries({x:box.x-5,y:box.y-5,width:box.width+10,height:box.height+10,fill:'none',stroke:'#376654','stroke-width':1.2,'stroke-dasharray':'5 4'}))rect.setAttribute(key,String(value));rect.setAttribute('vector-effect','non-scaling-stroke');g.append(rect);
 if(!locked&&enabled&&!touchMode){for(const [kind,x,y]of [['scale',box.x+box.width+5,box.y+box.height+5],['rotate',box.x+box.width/2,box.y-25]] as const){const circle=document.createElementNS(ns,'circle');circle.setAttribute('cx',String(x));circle.setAttribute('cy',String(y));circle.setAttribute('r','7');circle.setAttribute('fill','#fffef9');circle.setAttribute('stroke','#254d3e');circle.setAttribute('stroke-width','1.5');circle.setAttribute('data-placement-handle',kind);circle.style.pointerEvents='all';circle.style.cursor=kind==='scale'?'nwse-resize':'grab';g.append(circle)}}canvas.append(g)}
 function values(p=current()){get<HTMLInputElement>('placeX').value=String(Math.round(p.x));get<HTMLInputElement>('placeY').value=String(Math.round(p.y));get<HTMLInputElement>('placeScale').value=String(Math.round(p.scale*100));get<HTMLInputElement>('placeRotation').value=String(Math.round(p.rotation));get<HTMLButtonElement>('lockPlacement').textContent=p.locked?'Unlock piece':'Lock placement';get('lockPlacement').setAttribute('aria-pressed',String(p.locked));for(const id of ['placeX','placeY','placeScale','placeRotation','resetPlacement'])get<HTMLInputElement>(id).disabled=p.locked}
 const movableLayers=()=>LAYERS.filter(key=>canvas.querySelector(`[data-layer="${key}"]:not([data-placement-fixed="true"])`));
 function sync(){toggle.setAttribute('aria-pressed',String(enabled));toggle.textContent=touchMode?(enabled?'Done':'More'):(enabled?'Done arranging':'Arrange pieces');toggle.setAttribute('aria-label',touchMode?(enabled?'Close placement controls':'More placement controls'):(enabled?'Done arranging pieces':'Arrange pieces'));panel.hidden=!enabled;const available=movableLayers();if(selected&&!available.includes(selected))selected=available[0]||null;const select=get<HTMLSelectElement>('placementLayer');select.replaceChildren();for(const key of [...h.read().layerOrder].reverse().filter(k=>available.includes(k))){const option=document.createElement('option');option.value=key;option.textContent=LABELS[key];select.append(option)}if(selected)select.value=selected;get('placementFields').hidden=!available.length||!selected;get('placementEmpty').hidden=!!available.length&&!!selected;get('placementEmpty').textContent=available.length?emptyMessage:'Add an outfit from Wardrobe to arrange its pieces.';values();frame();const visibleOrder=h.read().layerOrder.filter(k=>available.includes(k)),index=selected?visibleOrder.indexOf(selected):-1;get<HTMLButtonElement>('layerBack').disabled=index<=0;get<HTMLButtonElement>('layerFront').disabled=index<0||index===visibleOrder.length-1;canvas.classList.toggle('arranging',enabled||touchMode);}
 function choose(key:LayerId){selected=key;emptyMessage='Choose a clothing piece on the model to arrange it.';h.select(key);sync()}
 function selectLayer(key:LayerId){selected=movableLayers().includes(key)?key:null;emptyMessage='Choose a clothing piece on the model to arrange it.';sync()}
 function selectField(field:string){selected=LAYERS.find(key=>FIELDS[key]===field&&movableLayers().includes(key))||null;emptyMessage=field==='shoeColour'?'Shoes stay in Styled with as a visual reference; they are not placed on the figure.':'Choose a clothing piece on the model to arrange it.';sync()}
 toggle.onclick=()=>{enabled=!enabled;h.stopDrawing();sync();const inspector=document.querySelector('.inspector');if(enabled){inspector?.classList.add('open');inspector?.setAttribute('aria-hidden','false');h.status(touchMode?'Drag pieces to move them. Pinch to resize or turn. Use More controls for precise placement.':'Select a piece and drag. Bottom handle resizes; top handle rotates. Reset placement puts it back.')}else if(touchMode){inspector?.classList.remove('open');inspector?.setAttribute('aria-hidden',String(window.matchMedia('(max-width: 620px)').matches))}};
 get<HTMLSelectElement>('placementLayer').onchange=()=>choose(get<HTMLSelectElement>('placementLayer').value as LayerId);
 for(const [id,key]of [['placeX','x'],['placeY','y'],['placeScale','scale'],['placeRotation','rotation']] as const)get<HTMLInputElement>(id).onchange=()=>{const value=Number(get<HTMLInputElement>(id).value);if(!selected||!Number.isFinite(value)){values();return}if(current().locked)return;h.commit(s=>{s.placements[selected!]=boundedPlacement({...current(),[key]:key==='scale'?value/100:value})})};
 get('resetPlacement').onclick=()=>{if(!selected||current().locked)return;h.commit(s=>{delete s.placements[selected!]});h.status('Original placement restored.')};
 get('resetAllPlacements').onclick=()=>{h.commit(s=>{s.placements={};s.layerOrder=[...LAYERS]});h.status('All pieces returned to their original placement and layer order.')};
 get('lockPlacement').onclick=()=>{if(selected)h.commit(s=>s.placements[selected!]={...current(),locked:!current().locked})};
 for(const [id,direction]of [['layerBack',-1],['layerFront',1]] as const)get(id).onclick=()=>h.commit(s=>{if(!selected)return;const visible=s.layerOrder.filter(key=>movableLayers().includes(key));const neighbor=visible[visible.indexOf(selected)+direction];if(!neighbor)return;const a=s.layerOrder.indexOf(selected),b=s.layerOrder.indexOf(neighbor);[s.layerOrder[a],s.layerOrder[b]]=[s.layerOrder[b]!,s.layerOrder[a]!]});
 const apply=(key:LayerId,p:Placement)=>{node()?.setAttribute('transform',placementTransform(key,p));if(key==='main'){canvas.querySelector('[data-neutral-cover]')?.setAttribute('visibility','visible');canvas.querySelector('[data-covered-legs]')?.removeAttribute('clip-path')}values(p);frame()};
 canvas.addEventListener('pointerdown',event=>{
  const element=event.target as Element;
  if(element.closest('[data-placement-fixed="true"]'))return;
  const handle=element.closest<SVGElement>('[data-placement-handle]')?.dataset.placementHandle;
  const key=element.closest<SVGElement>('[data-layer]:not([data-placement-fixed="true"])')?.dataset.layer as LayerId|undefined;
  if(touchMode&&event.pointerType==='touch'){
   if(!touchGesture){if(!key||touchPoints.size)return;touchSelected=true;choose(key)}
   else if(touchGesture.ids.length>=2)return;
   event.preventDefault();event.stopImmediatePropagation();
   const at=point(event);touchPoints.set(event.pointerId,at);try{canvas.setPointerCapture(event.pointerId)}catch{}
   if(!touchGesture){const initial={...current()};if(initial.locked){touchPoints.clear();h.status('Unlock this piece before moving it.');return}touchGesture={ids:[event.pointerId],key:selected!,initial,current:initial,start:[{x:at.x,y:at.y}]}}
   else {const previousId=touchGesture.ids[0]!,previous=touchPoints.get(previousId)!;touchGesture={ids:[previousId,event.pointerId],key:touchGesture.key,initial:{...touchGesture.current},current:{...touchGesture.current},start:[{x:previous.x,y:previous.y},{x:at.x,y:at.y}]}}
   return;
  }
  if(!enabled||event.button!==0||gesture||!canvas.getScreenCTM()||(!handle&&!key))return;
 event.preventDefault();event.stopImmediatePropagation();if(key)choose(key);if(!selected)return;const initial={...current()};if(initial.locked){h.status('Unlock this piece to change its placement.');return}canvas.setPointerCapture(event.pointerId);gesture={id:event.pointerId,kind:handle||'move',start:point(event),initial,current:initial,key:selected}
 },true);
 canvas.addEventListener('pointermove',event=>{
  if(touchMode&&touchPoints.has(event.pointerId)&&touchGesture){event.preventDefault();event.stopImmediatePropagation();const at=point(event);touchPoints.set(event.pointerId,at);const g=touchGesture;if(g.ids.length===1){const start=g.start[0]!,initial=g.initial;g.current=boundedPlacement({...initial,x:initial.x+at.x-start.x,y:initial.y+at.y-start.y})}else{const a=touchPoints.get(g.ids[0]!),b=touchPoints.get(g.ids[1]!);if(!a||!b)return;g.current=transformPlacementWithPointers(g.initial,g.start as [PlacementPoint,PlacementPoint],[{x:a.x,y:a.y},{x:b.x,y:b.y}])}apply(g.key,g.current);return}
  if(!gesture||gesture.id!==event.pointerId)return;event.preventDefault();event.stopImmediatePropagation();const at=point(event),g=gesture;const [ax,ay]=PIVOTS[g.key],cx=ax+g.initial.x,cy=ay+g.initial.y;let change:Partial<Placement>={};if(g.kind==='move')change={x:g.initial.x+at.x-g.start.x,y:g.initial.y+at.y-g.start.y};else if(g.kind==='scale')change={scale:g.initial.scale*Math.hypot(at.x-cx,at.y-cy)/Math.max(1,Math.hypot(g.start.x-cx,g.start.y-cy))};else {const delta=(Math.atan2(at.y-cy,at.x-cx)-Math.atan2(g.start.y-cy,g.start.x-cx))*180/Math.PI;change={rotation:((g.initial.rotation+delta+540)%360)-180}}g.current=boundedPlacement({...g.initial,...change});apply(g.key,g.current)
 },true);
 const finish=(event:PointerEvent,cancel:boolean)=>{if(!gesture||gesture.id!==event.pointerId)return;event.preventDefault();event.stopImmediatePropagation();const g=gesture;gesture=null;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);if(cancel){h.render();return}if(JSON.stringify(g.initial)!==JSON.stringify(g.current))h.commit(s=>s.placements[g.key]=g.current);else sync()};
 canvas.addEventListener('pointerup',e=>{if(touchMode&&touchPoints.has(e.pointerId)){e.preventDefault();e.stopImmediatePropagation();const g=touchGesture;if(g&&JSON.stringify(g.initial)!==JSON.stringify(g.current))h.commit(s=>s.placements[g.key]=g.current);touchGesture=null;touchPoints.clear();if(g)sync();return}finish(e,false)},true);
 canvas.addEventListener('pointercancel',e=>{if(touchMode&&touchPoints.has(e.pointerId)){touchGesture=null;touchPoints.clear();h.render();return}finish(e,true)},true);
 canvas.addEventListener('lostpointercapture',e=>{if(gesture&&gesture.id===e.pointerId){gesture=null;h.render()}});
 canvas.addEventListener('click',e=>{if(enabled||touchMode)e.stopImmediatePropagation()},true);
 canvas.setAttribute('tabindex','0');canvas.setAttribute('aria-label',touchMode?'Outfit illustration. Tap a piece, drag to move, and pinch to resize or turn.':'Outfit illustration. Use Arrange pieces for placement controls.');
 canvas.addEventListener('keydown',event=>{if(!enabled||!selected||current().locked)return;const delta:Record<string,[number,number]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};const d=delta[event.key];if(!d)return;event.preventDefault();event.stopImmediatePropagation();h.commit(s=>s.placements[selected!]=boundedPlacement({...current(),x:current().x+d[0]*(event.shiftKey?10:2),y:current().y+d[1]*(event.shiftKey?10:2)}));canvas.focus()},true);
 return {sync,selectField,selectLayer,stop(){enabled=false;sync()}};
}
