import type {Look} from './studio-state'
import {lookReference} from './studio-look-bank'

const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]!))
function lines(value:string,length:number){const words=value.trim().split(/\s+/).filter(Boolean),out:string[]=[];let row='';for(const word of words){if((row+' '+word).length>length&&row){out.push(row);row=word}else row+=(row?' ':'')+word}if(row)out.push(row);return out.length?out:['Not specified']}
const text=(x:number,y:number,value:string,size=18,weight=400)=>`<text x="${x}" y="${y}" font-size="${size}" font-weight="${weight}">${esc(value)}</text>`

/** One compact, readable sheet for a customer and tailor to discuss together. */
export function renderSketchSheet(look:Look,paper:string){const bank=lookReference(look.inspirationLook);let rightY=151,body='';for(const [label,value] of [['KEEP',look.directions.keep],['CHANGE',look.directions.change],['REMOVE',look.directions.remove],['CONFIRM TOGETHER',look.directions.confirm]]){body+=text(592,rightY,label,14,700);rightY+=25;for(const row of lines(value,49)){body+=text(592,rightY,row,17);rightY+=23}rightY+=21}
 if(look.notes.trim()){body+=text(592,rightY,'EXTRA NOTE',14,700);rightY+=25;for(const row of lines(look.notes,49)){body+=text(592,rightY,row,16);rightY+=22}}
 const referenceY=Math.max(928,rightY+37),referenceHeight=bank||look.reference?252:0,colourY=referenceY+referenceHeight+10;let references='';if(bank){references+=text(45,referenceY,'LOOK REFERENCE',14,700)+`<image x="45" y="${referenceY+16}" width="140" height="195" href="${bank.image}" preserveAspectRatio="xMidYMid meet"/>`+text(198,referenceY+45,bank.name,17,700)+text(198,referenceY+72,'Shape and mood reference',14)}if(look.reference){const x=bank?578:45;references+=text(x,referenceY,'YOUR PHOTO REFERENCE',14,700)+`<image x="${x}" y="${referenceY+16}" width="140" height="195" href="${look.reference.image}" preserveAspectRatio="xMidYMid meet"/>`+text(x+153,referenceY+45,'Colour and mood reference',14)}
 const samples=[...look.lookPalette,...(look.reference?.palette??[])].slice(0,10);let swatches='';if(samples.length){swatches=text(45,colourY,'SAMPLED COLOURS · CONFIRM REAL FABRIC',14,700);samples.forEach((colour,index)=>{const x=45+(index%5)*205,y=colourY+17+Math.floor(index/5)*38;swatches+=`<rect x="${x}" y="${y}" width="28" height="26" rx="5" fill="${esc(colour)}" stroke="#d3d5ca"/>`+text(x+35,y+18,colour.toUpperCase(),14)})}
 const totalHeight=colourY+(samples.length?Math.ceil(samples.length/5)*38+60:54);return `<svg xmlns="http://www.w3.org/2000/svg" width="1100" height="${totalHeight}" viewBox="0 0 1100 ${totalHeight}"><rect width="1100" height="${totalHeight}" fill="#fffdf8"/><g fill="#233c34" font-family="Arial,sans-serif">${text(45,52,'DRAPEON / STUDIO SKETCH',17,700)}${text(45,91,look.name.slice(0,60),30,700)}${text(592,89,'DESIGN DIRECTIONS',16,700)}<path d="M45 111H1055" stroke="#cbd1c5"/><rect x="44" y="130" width="510" height="778" rx="6" fill="#faf9f3" stroke="#d8ddd2"/><svg x="49" y="138" width="500" height="760" viewBox="0 0 500 760">${paper}</svg>${body}${references}${swatches}<path d="M45 ${totalHeight-39}H1055" stroke="#cbd1c5"/>${text(45,totalHeight-17,'Design intent · Confirm measurements, construction and fabric swatches with your tailor.',13)}</g></svg>`}
