import {isEveryday} from './studio-everyday-state'
import {NOTE_LABELS,type Look} from './studio-state'
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!))
const title=(v:string)=>v==='aline'?'A-line':v==='threequarter'?'Three-quarter':v.replaceAll('-',' ').replace(/^./,s=>s.toUpperCase())
export function accessoryDescriptions(l:Look){if(l.canvasMode==='paper')return [];if(isEveryday(l))return [l.earrings?'hoop earrings':'',l.beads?'pendant necklace':'',l.sunglasses?'sunglasses':'',l.bag!=='none'?`${l.bag==='shoulder'?'shoulder':l.bag} bag`:''].filter(Boolean);return [l.headwear?`${l.headStyle==='auto'?(l.figure==='feminine'?'gele':'fila'):l.headStyle} headwear`:'',l.earrings?`${l.earringStyle} earrings`:'',l.beads?`${l.necklaceLayers} ${l.beadFinish}-tone bead strands`:'',l.watch?'watch':'',l.sunglasses?'sunglasses':'',l.bracelet?'bracelet':'',l.belt?'belt':'',l.bag!=='none'?`${l.bag} bag`:'',l.wrap!=='none'?`${l.wrap} wrap`:'',l.cane?`${l.caneStyle} cane (relaxed grip)`:'',l.fan?'folding fan (relaxed grip)':'',l.chestPanel?'contrast chest panel':'',l.chestEmbroidery?'chest embroidery':''].filter(Boolean)}
export function colourRows(l:Look):{label:string;hex:string;name:string}[]{const rows:{label:string;hex:string;name:string}[]=[];const add=(key:string,label:string,hex:string)=>rows.push({label,hex,name:l.colourNames[key]||'Shade name to confirm'});
 if(isEveryday(l)){if(l.everydayPieces.top!=='none')add('colour','Main fabric',l.colour);if(l.everydayPieces.bottom!=='none')add('lowerColour','Bottom fabric',l.lowerColour);if(l.everydayPieces.shoes!=='none')add('shoeColour','Footwear',l.shoeColour);if(l.bag!=='none')add('bagColour','Bag',l.bagColour);return rows}
 if(l.canvasMode==='paper'){for(const [i,c] of [...new Set(l.lookPalette)].entries())rows.push({label:`Look colour ${i+1}`,hex:c,name:'Sampled from look reference · not approved fabric'});for(const [i,c] of [...new Set(l.reference?.palette??[])].entries())rows.push({label:`Reference colour ${i+1}`,hex:c,name:'Sampled from inspiration photo · not approved fabric'});for(const [i,c] of [...new Set(l.sketch.map(line=>line.colour))].entries())rows.push({label:'Sketch colour '+(i+1),hex:c,name:'Drawing ink'});return rows}if(l.outfit!=='blank'){add('colour','Main fabric',l.colour);if(l.outfit!=='dress'&&l.outfit!=='jumpsuit')add('lowerColour','Bottom fabric',l.lowerColour)}if(l.outer!=='none')add('outerColour','Outer fabric',l.outerColour);if(l.headwear)add('headColour','Headwear',l.headColour);add('shoeColour','Footwear',l.shoeColour);if(l.bag!=='none')add('bagColour','Bag',l.bagColour);if(l.wrap!=='none')add('wrapColour','Wrap',l.wrapColour);if(l.fan)add('fanColour','Fan',l.fanColour);if(l.chestPanel)add('panelColour','Chest panel',l.panelColour);if(l.chestEmbroidery||l.details.length)add('embroideryColour','Embroidery',l.embroideryColour);if(l.earrings||l.beads||l.belt||l.bracelet||l.watch)add('accentColour','Metal / details',l.accentColour);
 for(const [key,pattern,visible]of [['main',l.pattern,l.outfit!=='blank'],['bottom',l.bottomPattern,!['dress','blank','jumpsuit'].includes(l.outfit)],['outer',l.outerPattern,l.outer!=='none'],['head',l.headPattern,l.headwear]] as const)if(visible&&pattern!=='plain')add(key+'PatternInk',title(key)+' pattern',l.surfaces[key].ink);return rows}
export function fabricColourRows(l:Look){return l.canvasMode==='paper'?[]:colourRows(l).filter(r=>!['Footwear','Bag','Fan','Metal / details'].includes(r.label))}
/** Callouts are the part of a sketch a tailor can act on without guessing, so
 *  they travel as text alongside the image rather than only as pixels. */
export function calloutLines(l:Look){return l.sketch.filter(s=>s.tool==='note').map(s=>`${NOTE_LABELS[s.kind??'detail']}: ${s.text||'marked on the sketch'}`)}
export function briefHandoffNotes(l:Look){
 const fabricColours=fabricColourRows(l)
 const referenceColours=[...l.lookPalette.map((hex,i)=>`Look colour ${i+1} (sampled from look reference · not approved fabric) ${hex.toUpperCase()}`),...(l.reference?.palette??[]).map((hex,i)=>`Reference colour ${i+1} (sampled from inspiration photo · not approved fabric) ${hex.toUpperCase()}`)]
 const direction=(label:string,value:string,fallback:string)=>`${label}: ${(value||fallback).slice(0,180)}`
 const core=[`${l.name}: ${designLines(l).join('; ').slice(0,210)}`,direction('Keep',l.directions.keep,'See attached sheet'),direction('Change',l.directions.change,'See attached sheet'),direction('Remove',l.directions.remove,'See attached sheet'),direction('Confirm with tailor',l.directions.confirm,'Construction, measurements, fabric swatches and final fit')]
 const callouts=calloutLines(l)
 const extra=[...(callouts.length?[`Sketch callouts: ${callouts.join('; ')}`]:[]),...(fabricColours.length?[`Colour targets: ${fabricColours.map(r=>`${r.label} ${r.name} ${r.hex.toUpperCase()}`).join('; ')}`]:[]),...(referenceColours.length?[`Reference colours: ${referenceColours.join('; ')}`]:[]),`Accessories: ${accessoryDescriptions(l).join(', ')||'None'}`]
 const footer='\nFull design specification is in the attached Sketch Room sheet. Screen colours are approximate; approve real fabric swatches.'
 return `${[...core,...extra].join('\n').slice(0,1200-footer.length)}${footer}`
}
export function fabricTargetFingerprint(l:Look){if(isEveryday(l))return JSON.stringify({colours:fabricColourRows(l),pieces:{top:l.everydayPieces.top,bottom:l.everydayPieces.bottom}});const pieces=[...(l.outfit==='blank'?[]:['main']),...(['blank','dress','jumpsuit'].includes(l.outfit)?[]:['bottom']),...(l.outer==='none'?[]:['outer']),...(l.headwear?['head']:[])];return JSON.stringify({colours:fabricColourRows(l),surfaces:pieces.map(key=>({piece:key,pattern:key==='main'?l.pattern:key==='bottom'?l.bottomPattern:key==='outer'?l.outerPattern:l.headPattern,...l.surfaces[key as 'main'|'bottom'|'outer'|'head']}))})}
export function designLines(l:Look){if(isEveryday(l))return ['Easy everyday · realistic styling concept',`Top: ${l.everydayPieces.top==='shirt'?'Short-sleeve shirt':l.everydayPieces.top==='sleeveless'?'Sleeveless top':l.everydayPieces.top==='tee'?'Crew tee':l.everydayPieces.top==='blouse'?'Long-sleeve blouse':'None'}`,`Bottom: ${l.everydayPieces.bottom==='trousers'?'Wide-leg trousers':l.everydayPieces.bottom==='skirt'?'Midi skirt':l.everydayPieces.bottom==='shorts'?'Cotton shorts':'None'}`,`Footwear: ${{sandals:'Sandals',sneakers:'Canvas sneakers',flats:'Flats',loafers:'Loafers',none:'None'}[l.everydayPieces.shoes]}`,`Bag: ${({none:'None',tote:'Tote bag',shoulder:'Shoulder bag',crossbody:'Crossbody bag'} as Record<string,string>)[l.bag]??'None'}`,'One model and pose; selected pieces retain the shown shape and fabric texture','Placement and colour express styling intent; construction to confirm'];if(l.canvasMode==='paper')return [l.sketchUnderlay?'Sketch over uploaded paper':'Blank-page sketch',`${l.sketch.length} drawn marks`,...(l.inspirationLook?[`Look reference: ${title(l.inspirationLook)}`]:[]),...(l.reference?['Uploaded photo reference for colour and mood']:[]),'Garment construction to confirm with the tailor'];if(l.outfit==='blank')return ['Neutral fitted-base figure', 'No main garment selected',`Footwear: ${title(l.shoes)}; pose: ${title(l.pose)}`];const lines=[`Family: ${title(l.outfit)}`,`Shape: ${l.fit}; ${l.length} length; ${l.waist} waist`,...(['dress'].includes(l.outfit)?[`Silhouette: ${title(l.cut)}`]:[]),...(l.outfit==='separates'?[`Top: ${title(l.top)}; bottom: ${title(l.bottom)} (${l.bottomLength})${l.bottom==='skirt'?' / '+l.skirtShape:''}`]:[]),...(l.outfit==='jumpsuit'?[`Trouser intention: ${title(l.bottom)}`]:[]),`Sleeves: ${title(l.sleeve)}; neckline: ${title(l.neckline)}`,`Outer: ${title(l.outer)}; collar: ${title(l.collar)}`,`Construction: ${[l.pockets?'patch pockets':'',l.buttons?'button placket':''].filter(Boolean).join(', ')||'no added pockets or placket'}`,`Footwear: ${title(l.shoes)}; pose: ${title(l.pose)}`];
 for(const [key,p,visible] of [['main',l.pattern,true],['bottom',l.bottomPattern,!['dress','jumpsuit'].includes(l.outfit)],['outer',l.outerPattern,l.outer!=='none'],['head',l.headPattern,l.headwear]] as const)if(visible){const s=l.surfaces[key];lines.push(`${title(key)}: ${title(p)}, ${s.finish}${p!=='plain'?`, ${Math.round(s.scale*100)}%, ${s.rotation} degrees`:''}`)}return lines}
function wrap(v:string,n:number){const words=v.split(/\s+/).flatMap(w=>w.match(new RegExp(`.{1,${n}}`,'g'))||[]),lines:string[]=[];let line='';for(const w of words){if((line+' '+w).length>n&&line){lines.push(line);line=w}else line+=(line?' ':'')+w}if(line)lines.push(line);return lines}
export function renderTransferNotes(l:Look){return ['DRAPEON — DESIGN DIRECTIONS',l.name,'',...designLines(l),'',...(['keep','change','remove','confirm'] as const).map(k=>`${k.toUpperCase()}: ${l.directions[k]||'Not specified'}`),'',`ACCESSORIES: ${accessoryDescriptions(l).join(', ')||'None'}`,`Accessory sourcing: confirm what is owned, to be sourced, or to be made.`,`Placed details: ${l.details.length}; sketch strokes: ${l.sketch.length}`,'',...(calloutLines(l).length?['SKETCH CALLOUTS',...calloutLines(l)]:[]),'',l.canvasMode==='paper'?'REFERENCE COLOURS — sampled from inspiration, not approved fabric':'COLOUR TARGETS — approve real fabric swatches',...colourRows(l).map(r=>`${r.label}: ${r.name} (${r.hex.toUpperCase()})`),'',`SOURCE: ${l.reference?.sourceUrl||'No source URL provided'}`,`NOTES: ${l.notes||'None'}`,'','Illustrated design intent, not a fit prediction, sewing pattern or machine embroidery file. Tailor confirms construction, measurements, fabric and final fit.'].join('\n')}
export function renderLookSheet(l:Look,figure:string,inspirationImage?:string){let y=204,body='';const text=(x:number,y:number,v:string,size=18,bold=false)=>`<text x="${x}" y="${y}" font-size="${size}"${bold?' font-weight="700"':''}>${esc(v)}</text>`;
 for(const [label,value]of [['KEEP',l.directions.keep],['CHANGE',l.directions.change],['REMOVE',l.directions.remove],['CONFIRM WITH TAILOR',l.directions.confirm]]){body+=text(590,y,label,16,true);y+=28;for(const line of wrap(value||'Not specified',43)){body+=text(590,y,line);y+=24}y+=22}
 y=Math.max(910,y+10);body+=text(55,y,'GARMENT & ACCESSORY DETAILS',18,true);y+=32;for(const line of [...designLines(l),`Accessories: ${accessoryDescriptions(l).join(', ')||'None'}`,`Notes: ${l.notes||'None'}`])for(const part of wrap(line,99)){body+=text(55,y,part,17);y+=25}
 y+=24;body+=text(55,y,l.canvasMode==='paper'?'REFERENCE COLOURS — confirm fabric separately':'COLOUR TARGETS — confirm actual fabric swatches',18,true);y+=32;for(const r of colourRows(l))for(const line of wrap(`${r.label}: ${r.name} / ${r.hex.toUpperCase()}`,96)){body+=text(55,y,line,17);y+=26}
 if(l.reference){y+=30;body+=text(55,y,'ORIGINAL INSPIRATION',18,true)+`<image x="55" y="${y+20}" width="180" height="210" href="${l.reference.image}"/>`;let sy=y+48;for(const line of wrap(l.reference.sourceUrl||'Source link not provided',70)){body+=text(260,sy,line,15);sy+=22}y+=250}
 if(inspirationImage){y+=28;body+=text(55,y,'LOOK REFERENCE — FOR MOOD AND SHAPE',18,true)+`<image x="55" y="${y+20}" width="180" height="210" href="${inspirationImage}" preserveAspectRatio="xMidYMid meet"/>`;y+=250}
 y+=32;body+=text(55,y,'Design intent only. Tailor confirms construction, measurements and final fit.',15);return `<svg xmlns="http://www.w3.org/2000/svg" width="1100" height="${y+50}" viewBox="0 0 1100 ${y+50}"><rect width="1100" height="${y+50}" fill="#fffdf8"/><g fill="#233c34" font-family="Arial,sans-serif">${text(55,55,'DRAPEON / DESIGN DIRECTIONS',17)}${text(55,102,l.name.slice(0,60),30,true)}${text(55,134,'Review together before making · Screen colour is approximate',14)}<path d="M55 158H1045" stroke="#b8bcb1"/><svg x="20" y="175" width="520" height="710" viewBox="0 0 500 760">${figure}</svg>${body}</g></svg>`}
