import {savedLooks,saveLooks,saveDraft,recoveredDraft,startMode,canAttachToBrief,revisingOrderVersion,workingFromOrderVersion,storageNotice,native,exportNative,attachBrief,reviseOrder,proposeStylePlan} from './studio-host'
import {isEveryday,resetEveryday,removeEverydayPiece,everydayPiecePresent} from './studio-everyday-state'
import {mountEveryday} from './studio-everyday-ui'
import {mountSketchImport} from './studio-sketch-import'
import {mountPlacement} from './studio-placement-ui'
import {FIELDS} from './studio-placement-state'
import {mountColour} from './studio-colour'
import {surfaceKey} from './studio-design'
import {renderIllustration} from './studio-render'
import {COLOURS, DEFAULT_LOOK, STARTER_LOOKS, parseLook, snapshot, type Look} from './studio-state'
import {renderLookSheet,renderTransferNotes,designLines,accessoryDescriptions,colourRows,fabricColourRows,briefHandoffNotes as buildBriefHandoffNotes} from './studio-sheet'
import {photoPalette,photoColourAt} from './studio-photo'
document.body.classList.toggle('native-studio', native)
const get = <T extends HTMLElement>(id: string) => document.getElementById(id) as T
const canvas = document.getElementById('canvas') as unknown as SVGSVGElement
const orderVersion = revisingOrderVersion()
const sourceVersion = workingFromOrderVersion()
let colourPart: 'colour'|'lowerColour'|'outerColour'|'shoeColour'|'headColour'|'accentColour' = 'colour'
let drawMode=false, compareOpen=false
let pendingSketch: {before:Look;line:Look['sketch'][number]}|null=null
let placementUI:ReturnType<typeof mountPlacement>|null=null
let sketchImport:ReturnType<typeof mountSketchImport>|null=null
let everydayUI:ReturnType<typeof mountEveryday>|null=null
let uxReady=false
let syncColour:(()=>void)|null=null
let colourTarget='piece'
function readColour(){return colourTarget==='piece'?look[colourPart]:colourTarget==='pattern'?look.surfaces[surfaceKey(colourPart)].ink:look[colourTarget as 'bagColour'|'wrapColour'|'fanColour'|'embroideryColour'|'panelColour']}
function colourNameKey(){return colourTarget==='piece'?colourPart:colourTarget==='pattern'?surfaceKey(colourPart)+'PatternInk':colourTarget}
function writeColour(value:string){commit(s=>{if(colourTarget==='piece')s[colourPart]=value;else if(colourTarget==='pattern')s.surfaces[surfaceKey(colourPart)].ink=value;else s[colourTarget as 'bagColour'|'wrapColour'|'fanColour'|'embroideryColour'|'panelColour']=value;delete s.colourNames[colourNameKey()]})}
let look = snapshot(recoveredDraft()??DEFAULT_LOOK), selected = '', undo: Look[] = [], redo: Look[] = [], saved: Look[] = []
function showPanel(index:number){document.querySelectorAll<HTMLElement>('aside > .panel').forEach((panel,i)=>panel.hidden=i!==index);document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(button=>button.setAttribute('aria-pressed',String(Number(button.dataset.tab)===index)))}
document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(button=>button.onclick=()=>showPanel(Number(button.dataset.tab)))
function status(text: string) { get('status').textContent = text }
saved=savedLooks()
let draftTimer:ReturnType<typeof setTimeout>|undefined, draftSaving=false, draftAgain=false
function scheduleDraftSave(){if(draftTimer)clearTimeout(draftTimer);draftTimer=setTimeout(()=>{void persistDraft()},650)}
async function persistDraft(silent=false){if(draftSaving){draftAgain=true;return}draftSaving=true;if(!silent)status('Saving draft…');try{await saveDraft(snapshot(look));if(!silent)status(orderVersion ? 'Order changes saved on this device. Send the update to share them.' : sourceVersion ? 'Tailor working copy saved on this device. Review the design to send your style plan for approval.' : 'Draft saved on this device')}catch{status('Draft could not save. Use Save look to keep a named copy.')}finally{draftSaving=false;if(draftAgain){draftAgain=false;void persistDraft(silent)}}}
function commit(change: (value: Look) => void) { const before = snapshot(look); change(look); if(look.fan||look.cane)look.pose='resting';if(look.fan)look.cane=false;if((look.fan||look.cane)&&look.bag==='clutch')look.bag='none';for(const field of ['colour','lowerColour','outerColour','shoeColour','headColour','accentColour'] as const){if(before[field]!==look[field]&&before.colourNames[field]===look.colourNames[field])delete look.colourNames[field]} if (JSON.stringify(before) === JSON.stringify(look)) return; undo.push(before); if(undo.length>60) undo.shift(); redo = []; status(orderVersion ? 'Changes not sent to the order yet' : 'Unsaved changes'); render(); scheduleDraftSave() }
function patternField(): 'pattern'|'bottomPattern'|'outerPattern'|'headPattern' {return colourPart==='lowerColour'?'bottomPattern':colourPart==='outerColour'?'outerPattern':colourPart==='headColour'?'headPattern':'pattern'}
function illustration(poseOverride?:Look['pose']){return renderIllustration(look,poseOverride,selected)}
function renderCompare() {
 const tray=get('poseCompare');tray.hidden=!compareOpen;canvas.closest('section')?.classList.toggle('compare-open',compareOpen);get('compare').setAttribute('aria-pressed',String(compareOpen));if(!compareOpen){tray.replaceChildren();return}
 tray.replaceChildren();for(const [pose,label] of [['resting','Arms relaxed'],['open','Arms gently out'],['hand-hip','Hand on hip']] as const){
  const button=document.createElement('button');button.type='button';button.setAttribute('aria-pressed',String(look.pose===pose));button.setAttribute('aria-label',`Use ${label} pose`);button.disabled=(look.fan||look.cane)&&pose!=='resting';if(button.disabled)button.title='Remove the held accessory first'
  const preview=document.createElement('img');preview.alt='';preview.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 760">${illustration(pose)}</svg>`)
  const caption=document.createElement('span');caption.textContent=label;button.append(preview,caption);button.onclick=()=>commit(state=>state.pose=pose);tray.append(button)
 }
}
function render() {
 if(isEveryday(look)){compareOpen=false;if(!['colour','lowerColour','shoeColour','accentColour'].includes(colourPart))colourPart='colour';colourTarget=colourPart==='accentColour'?'bagColour':'piece';get<HTMLSelectElement>('colourTarget').value=colourTarget}
 if(colourPart==='lowerColour'&&['dress','jumpsuit'].includes(look.outfit)){colourPart='colour';colourTarget='piece';get<HTMLSelectElement>('colourTarget').value='piece'}
 get<HTMLInputElement>("panelColour").value=look.panelColour;get<HTMLSelectElement>("necklaceLayers").value=String(look.necklaceLayers);for(const id of ["earringStyle","beadFinish","caneStyle"] as const)get<HTMLSelectElement>(id).value=look[id];get<HTMLSelectElement>("wrap").value=look.wrap;get<HTMLInputElement>("wrapColour").value=look.wrapColour;get("fan").setAttribute("aria-pressed",String(look.fan));canvas.innerHTML=illustration();renderCompare(); if(uxReady)renderUX();placementUI?.sync();sketchImport?.sync()
 const reference=look.reference
 const palette=get('referencePalette');palette.replaceChildren();for(const [i,colour] of (reference?.palette??[]).entries()){const choice=document.createElement('div');choice.className='colour-choice';const button=document.createElement('button');button.type='button';button.style.background=colour;button.title=`Use ${colour} as the main colour`;button.setAttribute('aria-label',`Use sampled colour ${i+1}: ${colour}`);button.setAttribute('aria-pressed',String(i===0));button.onclick=()=>commit(state=>{state.colour=colour;if(state.reference)state.reference.palette=[colour,...state.reference.palette.filter(value=>value!==colour)]});const code=document.createElement('small');code.textContent=colour.toUpperCase();choice.append(button,code);palette.append(choice)}
 const vectorWardrobe=isEveryday(look),fixedArtwork=look.wardrobeArt!=='none'&&!vectorWardrobe,rasterArtwork=fixedArtwork&&look.wardrobeArt!=='occasion-teal';get('stage').classList.toggle('raster-inspiration',rasterArtwork);get('stageLabel').textContent=look.canvasMode==='paper'?'Blank sketch page':rasterArtwork?'OUTFIT INSPIRATION':fixedArtwork?'ILLUSTRATED OUTFIT SAMPLE':look.outfit==='blank'?'Figure with fitted base':'Illustrated styling concept';get('artworkNote').hidden=!fixedArtwork;get('artworkNote').textContent=rasterArtwork?'The clothes and accessories are styled together in this artwork. Clear outfit to build and arrange individual pieces.':fixedArtwork?'The generated gown is fixed artwork. Accessories remain editable; clear the outfit to change shape or fabric.':' '
 canvas.setAttribute('aria-label',isEveryday(look)?'Easy everyday model with individually editable clothing pieces.':rasterArtwork?`${look.name}, complete outfit inspiration artwork.`:'Your editable outfit illustration')
 get('stage').classList.toggle('with-reference',!!reference)
 get('referencePanel').hidden=!reference
 if(reference)get<HTMLImageElement>('referenceImage').src=reference.image
 else get<HTMLImageElement>('referenceImage').removeAttribute('src')
 get<HTMLButtonElement>('removeReference').disabled=!reference
 for(const [id,key] of [['referenceUrl','sourceUrl'],['referenceKeep','keep'],['referenceChange','change']] as const){const field=get<HTMLInputElement|HTMLTextAreaElement>(id);field.disabled=!reference;field.value=reference?.[key]??''}
 get('referenceStatus').textContent=reference?'Reference ready. Tap the image to sample a colour; describe what to keep and change in Review.':''
 canvas.style.cursor=drawMode?'crosshair':'default'
 get('draw').setAttribute('aria-pressed',String(drawMode))
 get<HTMLButtonElement>('clearSketch').disabled=!look.sketch.length
 get<HTMLTextAreaElement>('notes').value=look.notes
 get<HTMLInputElement>('hexColour').value=readColour().toUpperCase();get<HTMLInputElement>('customColour').value=readColour();get('currentColourCode').textContent=`Selected ${colourPart==='lowerColour'?'bottom':colourPart==='outerColour'?'outer layer':colourPart==='headColour'?'headwear':colourPart==='shoeColour'?'footwear':colourPart==='accentColour'?'detail':'main garment'}: ${readColour().toUpperCase()}`
 get<HTMLSelectElement>('top').disabled=look.outfit!=='separates'
 get<HTMLSelectElement>('bottom').disabled=look.outfit==='blank';get<HTMLSelectElement>('jumpsuitLeg').value=look.bottom;get<HTMLSelectElement>('bottomLength').disabled=look.bottom==='shorts';get<HTMLSelectElement>('length').disabled=look.outfit==='separates'&&look.top==='cropped';get<HTMLSelectElement>('waist').disabled=!['dress','jumpsuit'].includes(look.outfit)&&!look.pockets&&!look.buttons
 get<HTMLSelectElement>('pose').disabled=look.fan||look.cane
 get<HTMLSelectElement>('headStyle').value=look.headwear?look.headStyle:'none';get('headwear').textContent=look.headwear?'Remove headwear':'Add headwear'
 get('poseHint').textContent=look.cane||look.fan?'Remove the held accessory to change pose.':'All sleeve shapes support these three illustrated poses.'
 get('separatesHint').textContent=look.outfit==='separates'?'Mix a top and bottom independently.':'Choose Mix separate pieces to edit the top and bottom.'

 get<HTMLSelectElement>('cut').disabled=look.outfit!=='dress'
 get<HTMLSelectElement>('pattern').disabled=colourPart==='shoeColour'||colourPart==='accentColour'
 get<HTMLInputElement>('patternScale').disabled=look[patternField()]==='plain'||get<HTMLSelectElement>('pattern').disabled
 get<HTMLInputElement>('patternScale').value=String(look.surfaces[surfaceKey(colourPart)].scale)
 get<HTMLSelectElement>('finish').value=look.surfaces[surfaceKey(colourPart)].finish;get<HTMLInputElement>('patternRotation').value=String(look.surfaces[surfaceKey(colourPart)].rotation);get('rotationValue').textContent=`${look.surfaces[surfaceKey(colourPart)].rotation}°`;get('scaleValue').textContent=`${Math.round(look.surfaces[surfaceKey(colourPart)].scale*100)}%`
 get('cutHint').textContent=look.outfit==='dress'?'Choose how the skirt falls.':'Dress cuts become available when you choose a dress.'
 get('scaleHint').textContent=get<HTMLSelectElement>('pattern').disabled?'Fabric patterns apply to clothing and headwear.':look[patternField()]==='plain'?'Choose a patterned fabric to adjust its scale.':'Change motif size without changing the outfit shape.'

 for(const id of ['figure','body','pose','outfit','sleeve','neckline','cut','top','bottom','outer','shoes','bag','name','fit','length','bottomLength','waist','skirtShape','collar'] as const) (get(id) as HTMLInputElement).value=look[id]
 get<HTMLSelectElement>('pose').value=look.pose
 get<HTMLSelectElement>('pattern').value=look[patternField()]
 for(const id of ['headwear','beads','earrings','belt','bracelet','sunglasses','watch','cane','chestPanel','chestEmbroidery','pockets','buttons'] as const) get(id).setAttribute('aria-pressed',String(look[id]))
 for(const id of ['headwear','beads','earrings','belt','bracelet','sunglasses','watch','cane','chestPanel','chestEmbroidery','pockets','buttons'] as const) (get(id) as HTMLButtonElement).disabled=rasterArtwork
 get<HTMLButtonElement>('undo').disabled=!undo.length;get<HTMLButtonElement>('redo').disabled=!redo.length
 get<HTMLButtonElement>('detail').disabled=look.details.length>=30
 const detail=look.details.find(d=>d.id===selected);get<HTMLInputElement>('detailSize').disabled=!detail;get<HTMLInputElement>('detailSize').value=String(detail?.size??18);get<HTMLButtonElement>('removeDetail').disabled=!detail
 document.querySelectorAll<HTMLButtonElement>('[data-colour]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.colour===readColour())))
 document.querySelectorAll<HTMLButtonElement>('[data-skin]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.skin===look.skin)))
 const fixedFields=['figure','body','pose','sleeve','neckline','cut','top','bottom','outer','shoes','fit','length','bottomLength','waist','skirtShape','collar','headStyle','earringStyle','beadFinish','necklaceLayers','panelColour','detailSize','chestPanel','chestEmbroidery','pockets','buttons']
 for(const id of fixedFields)(get(id) as HTMLInputElement).disabled=fixedArtwork||isEveryday(look)
 get('colourSection').querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLButtonElement>('input,select,button').forEach(el=>el.disabled=fixedArtwork)
 get('proportionControls').querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLButtonElement>('input,select,button').forEach(el=>el.disabled=fixedArtwork)
 get<HTMLSelectElement>('outfit').disabled=rasterArtwork;Array.from(get<HTMLSelectElement>('outfit').options).forEach(option=>option.disabled=fixedArtwork&&!['blank','dress'].includes(option.value))
 get<HTMLSelectElement>('bag').disabled=rasterArtwork;get<HTMLSelectElement>('headStyle').disabled=rasterArtwork
 Array.from(get<HTMLSelectElement>('bag').options).forEach(option=>option.disabled=fixedArtwork&&!['none','shoulder'].includes(option.value))
 Array.from(get<HTMLSelectElement>('headStyle').options).forEach(option=>option.disabled=fixedArtwork&&!['none','gele'].includes(option.value))
 everydayUI?.sync();syncColour?.()
}
for(const id of ['figure','body','pose','outfit','sleeve','neckline','cut','top','bottom','outer','shoes','fit','length','bottomLength','waist','skirtShape','collar'] as const) get(id).addEventListener('change',()=>{if(isEveryday(look))return;const value=get<HTMLSelectElement>(id).value;commit(state=>{Object.assign(state,{[id]:value});if(id==='outfit'){state.canvasMode='figure';if(value!=='separates')state.outer=value==='agbada'?'agbada':'none';if(value==='jumpsuit')state.bottom='wide'}})})
get<HTMLSelectElement>('headStyle').onchange=()=>{const value=get<HTMLSelectElement>('headStyle').value;commit(state=>{state.headwear=value!=='none';if(value!=='none')state.headStyle=value as Look['headStyle']})}
get<HTMLSelectElement>('pattern').onchange=()=>{const value=get<HTMLSelectElement>('pattern').value as Look['pattern'];commit(state=>state[patternField()]=value)}
function syncTextFields(){if(uxReady){const colourName=get<HTMLInputElement>('colourName').value.trim().slice(0,70);look.colourNames[colourNameKey()]=colourName}const name=get<HTMLInputElement>('name').value.trim()||'Untitled look';const notes=get<HTMLTextAreaElement>('notes').value.slice(0,1000);const sourceUrl=get<HTMLInputElement>('referenceUrl').value.trim().slice(0,500),keep=get<HTMLTextAreaElement>('referenceKeep').value.slice(0,500),change=get<HTMLTextAreaElement>('referenceChange').value.slice(0,500);commit(state=>{state.name=name;state.notes=notes;if(state.reference){state.reference.sourceUrl=/^https?:\/\//i.test(sourceUrl)?sourceUrl:'';state.reference.keep=keep;state.reference.change=change;state.directions.keep=keep;state.directions.change=change}})}
get('addReference').onclick=()=>get<HTMLInputElement>('referenceFile').click()
get('removeReference').onclick=()=>commit(state=>state.reference=null)
get<HTMLImageElement>('referenceImage').onclick=event=>{const image=get<HTMLImageElement>('referenceImage');if(!look.reference||!image.naturalWidth||!image.naturalHeight)return;const bounds=image.getBoundingClientRect(),scale=Math.min(bounds.width/image.naturalWidth,bounds.height/image.naturalHeight),displayWidth=image.naturalWidth*scale,displayHeight=image.naturalHeight*scale,left=bounds.left+(bounds.width-displayWidth)/2,top=bounds.top+(bounds.height-displayHeight)/2,x=(event.clientX-left)/scale,y=(event.clientY-top)/scale;if(x<0||y<0||x>=image.naturalWidth||y>=image.naturalHeight){status('Tap inside the photo to sample a fabric colour.');return}const pixel=document.createElement('canvas');pixel.width=image.naturalWidth;pixel.height=image.naturalHeight;const context=pixel.getContext('2d');if(!context)return;context.drawImage(image,0,0);const colour=photoColourAt(context.getImageData(0,0,pixel.width,pixel.height).data,pixel.width,pixel.height,x,y);if(!colour)return;commit(state=>{state.colour=colour;if(state.reference)state.reference.palette=[colour,...state.reference.palette.filter(value=>value!==colour)].slice(0,5)});status(`Selected ${colour} from the photo. Create a draft to use it.`)}
get('blankFigure').onclick=()=>{if(isEveryday(look)){commit(state=>resetEveryday(state));selected='';render();status('Fresh canvas ready. The same model stays; all clothing pieces and the bag are removed.');return}commit(state=>{state.canvasMode='figure';state.wardrobeArt='none';state.outfit='blank';state.outer='none';state.headwear=false;state.beads=false;state.earrings=false;state.belt=false;state.bracelet=false;state.bag='none';state.fan=false;state.wrap='none';state.cane=false;state.watch=false;state.sunglasses=false;state.chestPanel=false;state.chestEmbroidery=false;state.pockets=false;state.buttons=false;state.details=[]});status('Outfit cleared. The figure keeps a modest fitted base.')}
get('blankPaper').onclick=()=>{commit(state=>{state.canvasMode='paper';state.wardrobeArt='none';state.sketchUnderlay=null;state.sketch=[];state.outfit='blank';state.outer='none';state.headwear=false;state.beads=false;state.earrings=false;state.belt=false;state.bracelet=false;state.bag='none';state.fan=false;state.wrap='none';state.cane=false;state.watch=false;state.sunglasses=false;state.chestPanel=false;state.chestEmbroidery=false;state.details=[]});status('Blank sketch page ready. Turn on Draw detail to sketch.')}

get<HTMLInputElement>('referenceFile').onchange=async()=>{const input=get<HTMLInputElement>('referenceFile'),file=input.files?.[0];input.value='';if(!file)return;try{
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15000000)throw new Error('Choose a JPEG, PNG, or WebP image smaller than 15 MB.')
 const bitmap=await createImageBitmap(file);const scale=Math.min(1,700/Math.max(bitmap.width,bitmap.height));const resized=document.createElement('canvas');resized.width=Math.max(1,Math.round(bitmap.width*scale));resized.height=Math.max(1,Math.round(bitmap.height*scale));const context=resized.getContext('2d');if(!context)throw new Error('This image could not be prepared.');context.fillStyle='#fff';context.fillRect(0,0,resized.width,resized.height);context.drawImage(bitmap,0,0,resized.width,resized.height);bitmap.close();const palette=photoPalette(context.getImageData(0,0,resized.width,resized.height).data,resized.width,resized.height)
 const image=[.82,.68,.5].map(quality=>resized.toDataURL('image/jpeg',quality)).find(value=>value.length<=300000);if(!image)throw new Error('This image is too detailed to store in a look. Try a smaller copy.')
 commit(state=>{state.reference={image,sourceUrl:'',keep:'',change:'',palette};state.directions={keep:'',change:'',remove:'',confirm:''}});status('New inspiration added. Add directions for this photo; The photo stays a colour and mood reference; Undo restores the previous one.')
 }catch(error){get('referenceStatus').textContent=error instanceof Error?error.message:'The image could not open.'}}
for(const id of ['referenceUrl','referenceKeep','referenceChange'])get(id).addEventListener('change',syncTextFields)
get<HTMLInputElement>('name').addEventListener('change',syncTextFields)
for(const id of ['headwear','beads','earrings','belt','bracelet','sunglasses','watch','cane','chestPanel','chestEmbroidery','pockets','buttons'] as const) get(id).onclick=()=>commit(state=>state[id]=!state[id])
function swatches(id:string,values:readonly string[],field:'skin'|'colour') { for(const value of values) {const button=document.createElement('button');button.className='swatch';button.style.background=value;button.style.setProperty('--colour',value);button.dataset[field]=value;button.setAttribute('aria-label',`${field==='skin'?'Skin tone':'Fabric colour'} ${value}`);button.onclick=()=>field==='colour'?writeColour(value):commit(state=>state.skin=value);get(id).append(button)} }
get<HTMLInputElement>('customColour').onchange=()=>{const value=get<HTMLInputElement>('customColour').value; if(/^#[0-9a-f]{6}$/i.test(value))writeColour(value)}
get<HTMLSelectElement>('colourPart').onchange=()=>{colourPart=get<HTMLSelectElement>('colourPart').value as typeof colourPart;render()}
swatches('colours',COLOURS,'colour');swatches('skins',['#4c3025','#855235','#b97e51','#d4a47e'],'skin')
get<HTMLInputElement>('patternScale').onchange=()=>{const value=Number(get<HTMLInputElement>('patternScale').value);commit(state=>state.surfaces[surfaceKey(colourPart)].scale=Math.max(.3,Math.min(2.5,value)))}
get('compare').onclick=()=>{compareOpen=!compareOpen;render()}
get('draw').onclick=()=>{placementUI?.stop();drawMode=!drawMode;render();status(drawMode?'Draw on the outfit. Up to 50 lines; each line can be undone.':'Move embroidery details or select a line to remove it.')}
get('clearSketch').onclick=()=>commit(state=>state.sketch=[])
get<HTMLTextAreaElement>('notes').onchange=syncTextFields
get('detail').onclick=()=>{if(look.details.length>=30)return;selected=`detail-${crypto.randomUUID()}`;commit(state=>state.details.push({id:selected,x:250,y:330,size:18}))}
function removeDetail(){commit(state=>state.details=state.details.filter(d=>d.id!==selected));selected='';render()}
get('removeDetail').onclick=removeDetail
get<HTMLInputElement>('detailSize').onchange=()=>{const value=Number(get<HTMLInputElement>('detailSize').value);commit(state=>{const d=state.details.find(d=>d.id===selected);if(d)d.size=value})}
function bodyPoint(event:PointerEvent){const matrix=canvas.getScreenCTM();const point=matrix?new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse()):new DOMPoint(250,300);const scale=look.canvasMode==='paper'?1:look.body==='full'?1.15:look.body==='slim'?.87:1;return {x:Math.round(Math.max(0,Math.min(500,(point.x-250*(1-scale))/scale))*10)/10,y:Math.round(Math.max(0,Math.min(740,point.y-(look.canvasMode==='paper'?0:20)))*10)/10}}
let drag: { id:string; before:Look; pointer:number } | null=null
canvas.onpointerdown=event=>{if(drawMode){if(look.sketch.length>=50){status('50-line limit reached. Remove a line or clear the sketch to draw more.');return}const line={colour:look.accentColour,width:3,points:[bodyPoint(event)]};pendingSketch={before:snapshot(look),line};look.sketch.push(line);canvas.setPointerCapture(event.pointerId);render();return}const target=(event.target as Element).closest<SVGGElement>('[data-id]');if(!target)return;selected=target.dataset.id!;drag={id:selected,before:snapshot(look),pointer:event.pointerId};canvas.setPointerCapture(event.pointerId);render()}
canvas.onpointermove=event=>{if(pendingSketch){const point=bodyPoint(event);const previous=pendingSketch.line.points[pendingSketch.line.points.length-1]!;if(pendingSketch.line.points.length<500&&Math.hypot(point.x-previous.x,point.y-previous.y)>.7){pendingSketch.line.points.push(point);render()}return}if(!drag)return;const matrix=canvas.getScreenCTM();if(!matrix)return;const point=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());const scale=look.body==='full'?1.15:look.body==='slim'?.87:1;const d=look.details.find(d=>d.id===drag!.id);if(d){d.x=Math.max(125,Math.min(375,(point.x-250*(1-scale))/scale));d.y=Math.max(175,Math.min(610,point.y-20));render()}}
function finishDrag(){if(pendingSketch){if(pendingSketch.line.points.length>1){undo.push(pendingSketch.before);if(undo.length>60)undo.shift();redo=[];status('Sketch added — unsaved changes');scheduleDraftSave()}else look=pendingSketch.before;pendingSketch=null;render();return}if(!drag)return;if(JSON.stringify(drag.before)!==JSON.stringify(look)){undo.push(drag.before);if(undo.length>60)undo.shift();redo=[];status('Unsaved changes');scheduleDraftSave()}drag=null;render()}
canvas.onpointerup=finishDrag;canvas.onpointercancel=()=>{if(pendingSketch)look=pendingSketch.before;pendingSketch=null;if(drag)look=drag.before;drag=null;render()}
canvas.onkeydown=event=>{const line=(event.target as Element).closest<SVGElement>('[data-line]');if(line&&(event.key==='Delete'||event.key==='Backspace')){event.preventDefault();const index=Number(line.dataset.line);commit(state=>state.sketch.splice(index,1));return}const target=(event.target as Element).closest<SVGGElement>('[data-id]');if(!target)return;selected=target.dataset.id!;if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();removeDetail();return}const deltas:Record<string,[number,number]>={ArrowUp:[0,-3],ArrowDown:[0,3],ArrowLeft:[-3,0],ArrowRight:[3,0]};const delta=deltas[event.key];if(!delta)return;event.preventDefault();commit(state=>{const d=state.details.find(v=>v.id===selected);if(d){d.x=Math.max(125,Math.min(375,d.x+delta[0]));d.y=Math.max(175,Math.min(610,d.y+delta[1]))}});canvas.querySelector<SVGGElement>(`[data-id="${selected}"]`)?.focus()}
canvas.addEventListener('focusin',event=>{const id=(event.target as Element).closest<SVGGElement>('[data-id]')?.dataset.id;if(id&&id!==selected){selected=id;get<HTMLInputElement>('detailSize').disabled=false;get<HTMLInputElement>('detailSize').value=String(look.details.find(d=>d.id===id)?.size??18);get<HTMLButtonElement>('removeDetail').disabled=false}})
get('undo').onclick=()=>{const previous=undo.pop();if(previous){redo.push(snapshot(look));look=previous;selected='';render();status('Undone — unsaved changes');scheduleDraftSave()}}
get('redo').onclick=()=>{const next=redo.pop();if(next){undo.push(snapshot(look));look=next;selected='';render();status('Redone — unsaved changes');scheduleDraftSave()}}
function savedButtons(){get('saves').replaceChildren();if(!saved.length){const empty=document.createElement('p');empty.textContent='No saved sketches yet. You can create one here or upload a photo directly in the brief.';get('saves').append(empty)}saved.forEach(design=>{const button=document.createElement('button');button.textContent=`Open ${design.name}`;button.onclick=()=>{commit(state=>Object.assign(state,snapshot(design)));selected='';render();status(`Opened ${design.name}`)};get('saves').append(button)})}
get('save').onclick=async()=>{syncTextFields();try{const next=[snapshot(look),...saved.filter(d=>d.name!==look.name)].slice(0,12);const warning=await saveLooks(next);saved=next;savedButtons();status(warning||`Saved ${look.name} to your account and this device`)}catch{status('Device storage is unavailable. Download the design file to keep your look.')}}
function download(contents:string,type:string,extension:string,filename='drapeon-look'){if(native){void exportNative(contents,type,extension).then(()=>status('Export saved to your chosen folder.')).catch(error=>status(error.message));return;}const url=URL.createObjectURL(new Blob([contents],{type}));const link=document.createElement('a');link.href=url;link.download=`${filename}.${extension}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
get('download').onclick=()=>{syncTextFields();download(JSON.stringify(look,null,2),'application/json','json');status('Editable design prepared for download')}
get('export').onclick=()=>{const clone=canvas.cloneNode(true) as SVGSVGElement;clone.querySelectorAll('[data-placement-ui]').forEach(n=>n.remove());clone.querySelectorAll('.detail').forEach(d=>{d.removeAttribute('tabindex');d.querySelector('circle[stroke-dasharray]')?.remove()});clone.setAttribute('width','1000');clone.setAttribute('height','1520');download(new XMLSerializer().serializeToString(clone),'image/svg+xml','svg');status('Illustration prepared for download — save the look to keep editing')}
get('previewSheet').onclick=()=>{syncTextFields();get<HTMLImageElement>('sheetImage').src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(renderLookSheet(look,illustration()));get<HTMLDialogElement>('sheetPreview').showModal()}
get('closeSheet').onclick=()=>get<HTMLDialogElement>('sheetPreview').close()
get('sheet').onclick=()=>{syncTextFields();download(renderLookSheet(look,illustration()),'image/svg+xml','svg','drapeon-look-sheet');status('Design sheet prepared for download — keep the editable design file too')}
get('previewHandoff').onclick=()=>{syncTextFields();get('handoffText').textContent=renderTransferNotes(look);get('copyHandoff').textContent='Copy notes';get<HTMLDialogElement>('handoffPreview').showModal()}
get('closeHandoff').onclick=()=>get<HTMLDialogElement>('handoffPreview').close()
get('downloadHandoff').onclick=()=>{syncTextFields();download(renderTransferNotes(look),'text/plain;charset=utf-8','txt','drapeon-design-handoff');status('Handoff notes prepared for download')}
get('copyHandoff').onclick=async()=>{try{await navigator.clipboard.writeText(get('handoffText').textContent||'');get('copyHandoff').textContent='Copied notes'}catch{get('copyHandoff').textContent='Copy unavailable — download notes instead'}}
get('import').onclick=()=>get<HTMLInputElement>('file').click()
get<HTMLInputElement>('file').onchange=async()=>{const input=get<HTMLInputElement>('file'),file=input.files?.[0];input.value='';if(!file)return;try{if(file.size>1000000)throw new Error('Choose a Drapeon design file smaller than 1 MB.');const design=parseLook(JSON.parse(await file.text()));commit(state=>Object.assign(state,design));selected='';render();status('Design opened. Save it to keep it on this device.')}catch(error){status(error instanceof Error?error.message:'The design could not open.')}}
for(const starter of STARTER_LOOKS){const button=document.createElement('button');button.textContent=starter.label;button.onclick=()=>{commit(state=>{const reference=state.reference;Object.assign(state,snapshot(starter.look));state.reference=reference});selected='';render()};get('starters').append(button)}
savedButtons();showPanel(0)

// The redesigned shell reuses the local drawing engine. No account or order writes.
const escapeHTML=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
const pieceLabels:Record<string,string>={colour:'Main',lowerColour:'Bottom',outerColour:'Outer',headColour:'Headwear',shoeColour:'Shoes',accentColour:'Accessories'}
const colourLabels:Record<string,string>={'#ba7d86':'Dusty rose','#23766b':'Deep teal','#b87536':'Warm ochre','#33486e':'Midnight blue','#ede0bd':'Warm ivory','#553750':'Aubergine','#3f332c':'Dark brown','#d1a650':'Soft gold','#2e3e47':'Charcoal blue','#e6dfcf':'Oatmeal','#f1ece2':'Soft white','#7e8671':'Sage green','#a6594d':'Terracotta','#362b35':'Deep plum'}
function colourDescription(field:string){return look.colourNames[field]||colourLabels[(look as any)[field]?.toLowerCase()]||'Custom colour — describe the shade'}
const curated:{name:string;group:string;caption:string;values:Partial<Look>}[]=[
 {name:'Easy everyday',group:'everyday',caption:'Shirt · wide trousers',values:{wardrobeArt:'easy-everyday',everydayPieces:{top:'shirt',bottom:'trousers',shoes:'sandals'},outfit:'separates',top:'shirt',collar:'pointed',buttons:true,bottom:'wide',colour:'#f1ece2',lowerColour:'#7e8671',shoes:'sandals',shoeColour:'#674a37',sleeve:'short',neckline:'v',pattern:'plain',bag:'crossbody',bagColour:'#674a37'}},
 {name:'Soft tailoring',group:'everyday',caption:'Jacket · trousers',values:{wardrobeArt:'soft-tailoring',outfit:'separates',top:'shirt',collar:'pointed',buttons:true,bottom:'trousers',outer:'jacket',colour:'#f1ece2',lowerColour:'#2e3e47',outerColour:'#2e3e47',shoes:'loafers',sleeve:'long',pattern:'plain',figure:'masculine'}},
 {name:'After hours',group:'occasion',caption:'Flared dress · heels',values:{wardrobeArt:'after-hours',outfit:'dress',cut:'flare',sleeve:'none',neckline:'square',colour:'#362b35',pattern:'plain',shoes:'heels',earrings:true,bag:'clutch'}},
 {name:'The long line',group:'everyday',caption:'Long tunic · trousers',values:{wardrobeArt:'long-line',outfit:'tunic',sleeve:'long',neckline:'round',colour:'#a6594d',lowerColour:'#e6dfcf',pattern:'plain',shoes:'sandals'}},
 {name:'Celebration',group:'heritage',caption:'Agbada · fila · beads',values:{wardrobeArt:'celebration',outfit:'agbada',outer:'agbada',figure:'masculine',colour:'#ba7d86',lowerColour:'#ba7d86',outerColour:'#ba7d86',headColour:'#ba7d86',sleeve:'long',pattern:'woven',outerPattern:'woven',headPattern:'woven',headwear:true,headStyle:'fila',beads:true,cane:true,watch:true,sunglasses:true,necklaceLayers:3,chestPanel:true,chestEmbroidery:true}},
 {name:'Teal occasion',group:'heritage',caption:'A-line gown · gele · accessories',values:{wardrobeArt:'occasion-teal',figure:'feminine',body:'balanced',outfit:'dress',cut:'aline',length:'long',fit:'fitted',colour:'#075c50',pattern:'ankara',shoeColour:'#075c50',headwear:true,headStyle:'gele',headColour:'#075c50',headPattern:'ankara',sleeve:'puff',neckline:'square',earrings:true,beads:true,bracelet:true,bag:'shoulder',shoes:'heels'}},
 {name:'City layers',group:'everyday',caption:'Long coat · ankle boots',values:{wardrobeArt:'city-layers',outfit:'separates',top:'tee',bottom:'trousers',outer:'coat',figure:'masculine',colour:'#e6dfcf',lowerColour:'#3f332c',outerColour:'#b87536',sleeve:'long',shoes:'boots',wrap:'scarf',wrapColour:'#553750'}},
 {name:'One-piece ease',group:'everyday',caption:'Wide-leg jumpsuit · bishop sleeves',values:{wardrobeArt:'one-piece-ease',outfit:'jumpsuit',bottom:'wide',colour:'#553750',sleeve:'bishop',neckline:'v',shoes:'heels',earrings:true,length:'long',fit:'relaxed'}},
 {name:'Light & gathered',group:'everyday',caption:'Cropped blouse · A-line skirt',values:{wardrobeArt:'light-gathered',outfit:'separates',top:'blouse',bottom:'skirt',skirtShape:'aline',length:'short',bottomLength:'midi',colour:'#f1ece2',lowerColour:'#a6594d',bottomPattern:'floral',sleeve:'puff',shoes:'sandals',bag:'crossbody'}},
 {name:'Weekend light',group:'everyday',caption:'T-shirt · shorts · trainers',values:{wardrobeArt:'weekend-light',outfit:'separates',top:'tee',bottom:'shorts',figure:'masculine',colour:'#33486e',lowerColour:'#e6dfcf',sleeve:'short',length:'midi',shoes:'trainers',shoeColour:'#f1ece2',sunglasses:true}},
 {name:'Soft volume',group:'occasion',caption:'A-line midi · bell sleeves',values:{wardrobeArt:'soft-volume',outfit:'dress',cut:'aline',length:'midi',fit:'relaxed',sleeve:'bell',neckline:'boat',colour:'#ba7d86',shoes:'heels',bag:'clutch',bagColour:'#553750',earrings:true,earringStyle:'hoop'}},
 {name:'Clean lines',group:'occasion',caption:'Pencil dress · cap sleeves',values:{wardrobeArt:'clean-lines',outfit:'dress',cut:'pencil',length:'midi',sleeve:'cap',neckline:'sweetheart',colour:'#33486e',shoes:'heels',earrings:true,bracelet:true,fit:'fitted'}}
]
let activeRoom='wardrobe',activeFilter='all',activeStarter='',customised=false
const mobileStudio=()=>window.matchMedia('(max-width: 620px)').matches
function closeMobileLibrary(){const library=document.querySelector('.library');library?.classList.remove('mobile-open');library?.setAttribute('aria-hidden',String(mobileStudio()));get('mobileLibraryToggle').setAttribute('aria-expanded','false')}
function openMobileLibrary(){if(!mobileStudio())return;const inspector=document.querySelector('.inspector');inspector?.classList.remove('open');inspector?.setAttribute('aria-hidden','true');const library=document.querySelector('.library');library?.classList.add('mobile-open');library?.setAttribute('aria-hidden','false');get('mobileLibraryToggle').setAttribute('aria-expanded','true')}
function setRoom(room:string){activeRoom=room;document.querySelectorAll<HTMLElement>('[data-room-panel]').forEach(p=>p.hidden=p.dataset.roomPanel!==room);document.querySelectorAll<HTMLElement>('[data-room]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.room===room)))}
const thumbCache=new Map<string,string>();
function thumbFor(values:Partial<Look>){const cacheKey=JSON.stringify(values);if(thumbCache.has(cacheKey))return thumbCache.get(cacheKey)!;const previous=look;look={...snapshot(DEFAULT_LOOK),pattern:'plain',bottomPattern:'plain',outerPattern:'plain',headPattern:'plain',...values};const markup=illustration();look=previous;const box=values.wardrobeArt&&values.wardrobeArt!=='none'&&values.wardrobeArt!=='occasion-teal'?'0 0 500 760':'60 0 380 760';const url='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${box}">${markup}</svg>`);thumbCache.set(cacheKey,url);return url}
function fillCards(){const host=get('lookCards');host.replaceChildren();curated.filter(c=>activeFilter==='all'||c.group===activeFilter).sort((a,b)=>['everyday','occasion','heritage'].indexOf(a.group)-['everyday','occasion','heritage'].indexOf(b.group)).forEach(c=>{const b=document.createElement('button');b.className='look-card';b.setAttribute('aria-label',`Start ${c.name}`);b.setAttribute('aria-pressed',String(c.name===activeStarter));const img=document.createElement('img');img.src=thumbFor(c.values);img.alt='';const thumb=document.createElement('span');thumb.className='thumb';thumb.append(img);const title=document.createElement('strong');title.textContent=c.name;const caption=document.createElement('small');caption.textContent=c.caption;b.append(thumb,title,caption);b.onclick=()=>{commit(state=>{const ref=state.reference,figure=state.figure,skin=state.skin,body=state.body;Object.assign(state,snapshot(DEFAULT_LOOK),{pattern:'plain',bottomPattern:'plain',outerPattern:'plain',headPattern:'plain'},c.values,{name:c.name,reference:ref});if(isEveryday(state))state.everydayPieces={...state.everydayPieces};if(customised&&!c.values.wardrobeArt)Object.assign(state,{figure,skin,body})});activeStarter=c.name;selected='';drawMode=false;closeMobileLibrary();selectPiece('colour',false);fillCards();render();status(c.values.wardrobeArt==='easy-everyday'?`${c.name} loaded. Choose a top, bottom, shoes, bag or Accessories. Pieces stay editable on the model.`:c.values.wardrobeArt&&c.values.wardrobeArt!=='occasion-teal'?`${c.name} loaded as complete outfit inspiration. Clear the outfit to create an editable look.`:c.values.wardrobeArt?'Generated gown loaded. Its accessories remain separately editable.':`${c.name} is yours to change. Tap a piece below the figure to edit it.`)};host.append(b)})}
function selectPiece(field:typeof colourPart,open=true){closeMobileLibrary();colourPart=field;placementUI?.selectField(field);if(isEveryday(look)&&!everydayPiecePresent(look,field)){document.querySelector<HTMLElement>('.inspector')!.dataset.mode='shape';get('editShape').setAttribute('aria-pressed','true');get('editColour').setAttribute('aria-pressed','false')}colourTarget='piece';get<HTMLSelectElement>('colourTarget').value='piece';get<HTMLSelectElement>('colourPart').value=field;render();if(open){const inspector=document.querySelector('.inspector');inspector?.classList.add('open');inspector?.setAttribute('aria-hidden','false')}}
function renderUX(){
 get('lookTitle').textContent=look.name;get<HTMLInputElement>('inkColour').value=look.accentColour;const vectorWardrobe=isEveryday(look),fixedArt=look.wardrobeArt!=='none'&&!vectorWardrobe,rasterArt=fixedArt&&look.wardrobeArt!=='occasion-teal';get('pieceBar').hidden=look.canvasMode==='paper'||rasterArt;get('pieceBar').previousElementSibling!.textContent=look.canvasMode==='paper'?'Draw on the page. Undo removes your last stroke.':rasterArt?'Outfit inspiration · clear outfit to remix':'Choose a piece below to edit it';get('paperHint').hidden=look.canvasMode!=='paper'||look.sketch.length>0||!!look.sketchUnderlay;get('paperHint').querySelector('small')!.textContent=drawMode?'Draw directly on the page. Undo is always here.':'Choose Sketch to put your first line down.';
 const names:Record<string,string>={colour:look.outfit==='jumpsuit'?'Your jumpsuit':look.outfit==='dress'?'Your dress':look.outfit==='blank'?'Start with a shape':'Your top',lowerColour:'Your bottom piece',outerColour:'Your outer layer',shoeColour:'Your footwear',headColour:'Your headwear',accentColour:'The finishing touches'};
 const absent=colourPart==='colour'&&look.outfit==='blank'||colourPart==='lowerColour'&&look.outfit==='blank'||colourPart==='outerColour'&&look.outer==='none'||colourPart==='headColour'&&!look.headwear;get('colourSection').hidden=absent;get('pieceDescription').textContent=absent?'Choose a piece to start exploring its colour and details.':'The shape, the shade, the little things.';get('mainControls').querySelector<HTMLElement>('.pair')!.hidden=look.outfit==='blank';get('pieceTitle').textContent=colourTarget==='bagColour'?'Your bag':names[colourPart];get<HTMLInputElement>('colourName').value=look.colourNames[colourNameKey()]||'';get<HTMLInputElement>('colourName').placeholder=colourDescription(colourPart);
 for(const [id,field]of Object.entries({mainControls:'colour',bottomControls:'lowerColour',outerControls:'outerColour',headControls:'headColour',shoeControls:'shoeColour',accessoryControls:'accentColour'}))get(id).hidden=field!==colourPart;
 get('jumpsuitControls').hidden=look.outfit!=='jumpsuit'||colourPart!=='colour';get<HTMLSelectElement>('length').hidden=colourPart!=='colour';document.querySelector<HTMLLabelElement>('label[for="length"]')!.hidden=colourPart!=='colour';get('dressControls').hidden=look.outfit!=='dress';get('topControls').hidden=look.outfit!=='separates';get('proportionControls').hidden=!['colour','lowerColour'].includes(colourPart)||look.outfit==='blank';for(const id of ['fit','waist','collar','pockets','buttons']){get(id).hidden=colourPart!=='colour';document.querySelector<HTMLLabelElement>(`label[for="${id}"]`)?.toggleAttribute('hidden',colourPart!=='colour')}get('skirtShape').hidden=colourPart!=='lowerColour'||look.bottom!=='skirt';document.querySelector<HTMLLabelElement>('label[for="skirtShape"]')!.hidden=get('skirtShape').hidden;get('fabricControls').hidden=['shoeColour','accentColour'].includes(colourPart);
 const removal=get<HTMLButtonElement>('removePiece');removal.hidden=['shoeColour','lowerColour'].includes(colourPart);removal.textContent=colourPart==='colour'?'Clear outfit to neutral base':colourPart==='accentColour'?'Remove accessories':'Remove this piece';
 const fields=(vectorWardrobe?['colour','lowerColour','shoeColour','accentColour']:['colour',...(look.outfit==='dress'||look.outfit==='jumpsuit'?[]:['lowerColour']),'outerColour','shoeColour','headColour','accentColour']) as (typeof colourPart)[];
 const host=get('pieceBar');host.classList.toggle('everyday-piece-bar',vectorWardrobe);host.replaceChildren();for(const field of fields){const b=document.createElement('button');b.setAttribute('aria-pressed',String(field===colourPart));const dot=document.createElement('span');dot.className='piece-dot';dot.style.background=look[field];b.append(dot,document.createTextNode(vectorWardrobe&&field==='colour'?'Top':pieceLabels[field]));b.onclick=()=>selectPiece(field);host.append(b)}
 if(look.bag!=='none'||vectorWardrobe){const b=document.createElement('button');b.textContent='Bag';b.setAttribute('aria-pressed',String(colourTarget==='bagColour'));b.onclick=selectBag;host.append(b)}
}
document.querySelectorAll<HTMLElement>('[data-room]').forEach(b=>b.onclick=()=>setRoom(b.dataset.room!));
if(mobileStudio()){closeMobileLibrary();document.querySelector('.inspector')?.setAttribute('aria-hidden','true')}
get('mobileLibraryToggle').onclick=openMobileLibrary;get('mobileLibraryClose').onclick=()=>{closeMobileLibrary();get<HTMLButtonElement>('mobileLibraryToggle').focus()};
document.querySelectorAll<HTMLElement>('[data-filter]').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter!;document.querySelectorAll('[data-filter]').forEach(other=>other.setAttribute('aria-pressed',String(other===b)));fillCards()});
get('closeInspector').onclick=()=>{document.querySelector('.inspector')?.classList.remove('open');document.querySelector('.inspector')?.setAttribute('aria-hidden',String(mobileStudio()));get('pieceBar').querySelector<HTMLButtonElement>('[aria-pressed="true"]')?.focus()};
get('referenceShortcut').onclick=()=>setRoom('reference');
get<HTMLInputElement>('colourName').oninput=()=>{const value=get<HTMLInputElement>('colourName').value.trim().slice(0,70);commit(s=>s.colourNames[colourNameKey()]=value)};
for(const id of ['figure','body'])get(id).addEventListener('change',()=>customised=true);
get('removePiece').onclick=()=>{if(isEveryday(look)){commit(s=>removeEverydayPiece(s,colourPart));status('Piece removed. Add it again from Pieces, or use Undo.');return}if(colourPart==='colour')get('blankFigure').click();else commit(s=>{if(colourPart==='outerColour')s.outer='none';if(colourPart==='headColour')s.headwear=false;if(colourPart==='accentColour'){s.beads=false;s.earrings=false;s.belt=false;s.bracelet=false;s.bag='none';s.fan=false;s.wrap='none';s.cane=false;s.watch=false;s.sunglasses=false;s.chestPanel=false;s.chestEmbroidery=false;s.details=[]}})};
function selectBag(){selectPiece('accentColour');placementUI?.selectLayer('bag');colourTarget='bagColour';get<HTMLSelectElement>('colourTarget').value=colourTarget;render()}
canvas.addEventListener('click',e=>{if(drawMode)return;const target=e.target as Element;if(target.closest<SVGGElement>('[data-layer="bag"]')){selectBag();return}const field=target.closest<SVGGElement>('[data-piece]')?.dataset.piece;if(field)selectPiece(field as typeof colourPart)});
get<HTMLInputElement>('inkColour').oninput=()=>{const value=get<HTMLInputElement>('inkColour').value;commit(s=>s.accentColour=value)};
get('zoom').onclick=()=>{const zoomed=get('stage').classList.toggle('zoomed');get('zoom').setAttribute('aria-pressed',String(zoomed));get('zoom').setAttribute('aria-label',zoomed?'Reset outfit zoom':'Zoom into outfit')};
const closeWelcome=()=>get<HTMLDialogElement>('welcome').close();
get('newLook').onclick=()=>get<HTMLDialogElement>('welcome').showModal();get('closeWelcome').onclick=closeWelcome;
get('startLooks').onclick=()=>{closeWelcome();setRoom('wardrobe');openMobileLibrary()};get('startPhoto').onclick=()=>{closeWelcome();setRoom('reference');openMobileLibrary();get('addReference').click()};get('startSketch').onclick=()=>{closeWelcome();setRoom('sketch');openMobileLibrary();get('uploadSketch').click()};
get('startFigure').onclick=()=>{closeWelcome();drawMode=false;get('blankFigure').click();setRoom('figure');openMobileLibrary()};
function paper(){get('blankPaper').click();drawMode=true;commit(s=>s.accentColour='#233c34');render();setRoom('sketch');openMobileLibrary();status('Blank page ready. Draw directly on the canvas; Undo removes a stroke.')}
get('startPaper').onclick=()=>{closeWelcome();paper()};get('sketchBlank').onclick=paper;
get('openSaved').onclick=()=>get<HTMLDialogElement>('saveDialog').showModal();get('saveQuick').onclick=()=>get<HTMLDialogElement>('saveDialog').showModal();
document.querySelectorAll<HTMLElement>('[data-close]').forEach(b=>b.onclick=()=>get<HTMLDialogElement>(b.dataset.close!).close());
const oldSave=get('save').onclick;get('save').onclick=async e=>{if(draftTimer)clearTimeout(draftTimer);await oldSave?.call(get('save'),e);await persistDraft(true);get<HTMLDialogElement>('saveDialog').close()};
get('saves').addEventListener('click',e=>{if((e.target as Element).closest('button')){get<HTMLDialogElement>('saveDialog').close();activeStarter='';fillCards()}});
get<HTMLDialogElement>('reviewDialog').addEventListener('close',syncReview);
function review(){syncTextFields();const host=get('reviewBody');const src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 760">${illustration()}</svg>`);host.innerHTML=`<div class="review-grid"><section><h3>Your requested design</h3><div class="review-image"><img alt="Requested outfit illustration" src="${src}"></div><div class="review-colours">${colourRows(look).map(r=>`<span><b>${escapeHTML(r.label)}</b><br>${escapeHTML(r.name)}<br>${escapeHTML(r.hex.toUpperCase())}</span>`).join('')}</div><p class="fine">Approximate screen colours. Fabric swatch approval is needed before cutting.</p></section><section><h3>The details that matter</h3><details><summary>Garment and accessory specification</summary><ul>${designLines(look).map(line=>`<li>${escapeHTML(line)}</li>`).join('')}<li>${escapeHTML(accessoryDescriptions(look).join(', ')||'No accessories')}</li></ul></details>${look.reference?`<img class="review-reference" alt="Original inspiration reference" src="${look.reference.image}"><p class="fine">Original inspiration — describe what carries over.</p>`:'<p class="fine">No source photo. Describe the intention behind your original idea.</p>'}${(['keep','change','remove','confirm'] as const).map((key,i)=>`<label for="direction-${key}">${i+1}. ${({keep:'Keep',change:'Change',remove:'Remove',confirm:'Ask the tailor to confirm'})[key]}</label><textarea id="direction-${key}" maxlength="300" rows="2" placeholder="${({keep:'e.g. silhouette, neckline, fabric feel',change:'e.g. length, fit, fabric or sleeve detail',remove:'e.g. remove the belt',confirm:'e.g. construction, lining, fabric and movement'})[key]}">${escapeHTML(look.directions[key]||(key==='keep'?look.reference?.keep:key==='change'?look.reference?.change:'')||'')}</textarea>`).join('')}</section></div>`;
 for(const k of ['keep','change','remove','confirm'] as const)get<HTMLTextAreaElement>(`direction-${k}`).oninput=()=>{const value=get<HTMLTextAreaElement>(`direction-${k}`).value;commit(s=>{s.directions[k]=value;if(s.reference&&k==='keep')s.reference.keep=value;if(s.reference&&k==='change')s.reference.change=value})};get<HTMLDialogElement>('reviewDialog').showModal();}
function usedColours():(typeof colourPart)[]{return [...(look.outfit==='blank'?[]:['colour']),...(look.outfit==='dress'||look.outfit==='jumpsuit'||look.outfit==='blank'?[]:['lowerColour']),...(look.outer==='none'?[]:['outerColour']),...(look.headwear?['headColour']:[]),'shoeColour','accentColour'] as (typeof colourPart)[]}
function syncReview(){for(const k of ['keep','change','remove','confirm'] as const){const el=document.getElementById(`direction-${k}`) as HTMLTextAreaElement|null;if(el){look.directions[k]=el.value.slice(0,300);if(look.reference&&(k==='keep'||k==='change'))look.reference[k]=look.directions[k];let printable=el.nextElementSibling as HTMLElement|null;if(!printable?.classList.contains('print-value')){printable=document.createElement('div');printable.className='print-value';el.after(printable)}printable.textContent=el.value||'Not specified'}}}
function notesText(){return renderTransferNotes(look)}
get('review').onclick=review;get('editReview').onclick=()=>{syncReview();get<HTMLDialogElement>('reviewDialog').close()};get('textReview').onclick=()=>{syncReview();download(notesText(),'text/plain','txt','drapeon-design-directions')};
get('pngReview').onclick=async()=>{syncReview();const button=get<HTMLButtonElement>('pngReview');button.disabled=true;button.textContent='Preparing image…';try{const svg=reviewSVG(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(new Error('Image rendering failed'));img.src=url});const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d');if(!ctx)throw Error('Canvas unavailable');ctx.drawImage(img,0,0);const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('PNG export unavailable')),'image/png'));const data=c.toDataURL('image/png');get<HTMLImageElement>('pngImage').src=data;get<HTMLAnchorElement>('pngSave').href=data;get<HTMLDialogElement>('pngPreview').showModal();button.textContent='View PNG sheet'}finally{URL.revokeObjectURL(url)}}catch{button.textContent='PNG unavailable — use SVG or Print'}finally{button.disabled=false}};
get('printReview').onclick=()=>{syncReview();window.print()};
get('downloadReview').onclick=()=>{syncReview();download(reviewSVG(),'image/svg+xml','svg','drapeon-design-sheet')};
function briefHandoffNotes(){return buildBriefHandoffNotes(look)}
get<HTMLButtonElement>('attachToBrief').hidden=!canAttachToBrief();
get<HTMLButtonElement>('reviseOrder').hidden=!revisingOrderVersion();
get<HTMLElement>('orderRevisionFields').hidden=!revisingOrderVersion();
get<HTMLElement>('tailorProposalFields').hidden=!sourceVersion;
get<HTMLButtonElement>('proposeStylePlan').hidden=!sourceVersion;
async function reviewPNG(){const url=URL.createObjectURL(new Blob([reviewSVG()],{type:'image/svg+xml'}));try{const image=new Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(Error('The design sheet could not be rendered.'));image.src=url});const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const context=canvas.getContext('2d');if(!context)throw Error('Image export is unavailable.');context.drawImage(image,0,0);const data=canvas.toDataURL('image/png');if(data.length>9_000_000)throw Error('This sheet is too large to attach. Shorten the notes or remove the inspiration image, then try again.');return data}finally{URL.revokeObjectURL(url)}}
get('reviseOrder').onclick=async()=>{syncReview();const note=get<HTMLTextAreaElement>('orderRevisionNote').value.trim();if(note.length<5){status('Describe what changed in at least five characters.');get<HTMLTextAreaElement>('orderRevisionNote').focus();return}const button=get<HTMLButtonElement>('reviseOrder');button.disabled=true;button.textContent='Sending updated design…';try{await reviseOrder(await reviewPNG(),snapshot(look),note);button.textContent='Design sent to your order'}catch(error){button.disabled=false;button.textContent='Send updated design to order';status(error instanceof Error?error.message:'The design could not be sent.')}};
get('proposeStylePlan').onclick=async()=>{syncReview();const note=get<HTMLTextAreaElement>('tailorProposalNote').value.trim();if(note.length<10){status('Explain your style plan in at least ten characters.');get<HTMLTextAreaElement>('tailorProposalNote').focus();return}const button=get<HTMLButtonElement>('proposeStylePlan');button.disabled=true;button.textContent='Sending style plan…';try{await proposeStylePlan(await reviewPNG(),note);button.textContent='Style plan sent for customer approval'}catch(error){button.disabled=false;button.textContent='Send style plan for approval';status(error instanceof Error?error.message:'The style plan could not be sent.')}};
get('attachToBrief').onclick=async()=>{syncReview();const button=get<HTMLButtonElement>('attachToBrief');button.disabled=true;button.textContent='Preparing brief reference…';try{const svg=reviewSVG(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const image=new Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(Error('The design sheet could not be rendered.'));image.src=url});const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const context=canvas.getContext('2d');if(!context)throw Error('Image export is unavailable.');context.drawImage(image,0,0);const data=canvas.toDataURL('image/png');if(data.length>9_000_000)throw Error('This sheet is too large to attach. Shorten the notes or remove the inspiration image, then try again.');attachBrief(data,briefHandoffNotes(),`${look.name} — Sketch Room sheet`,snapshot(look));button.textContent='Returning to your brief…'}finally{URL.revokeObjectURL(url)}}catch(error){button.disabled=false;button.textContent='Attach design to brief';status(error instanceof Error?error.message:'The design could not be attached.')}};
function reviewSVG(){return renderLookSheet(look,illustration())}
get('panelColour').onchange=()=>commit(s=>s.panelColour=get<HTMLInputElement>('panelColour').value);
get('necklaceLayers').onchange=()=>commit(s=>{s.necklaceLayers=Number(get<HTMLSelectElement>('necklaceLayers').value);s.beads=true});
get('cane').onclick=()=>{commit(s=>{s.cane=!s.cane;if(s.cane){s.pose='resting';s.fan=false;if(s.bag==='clutch')s.bag='none'}});status('Cane grip uses relaxed arms. Undo restores your previous pose.')};
for(const id of ['earringStyle','beadFinish','caneStyle'] as const)get(id).onchange=()=>commit(s=>{(s as any)[id]=get<HTMLSelectElement>(id).value;if(id==='earringStyle')s.earrings=true;if(id==='beadFinish')s.beads=true;if(id==='caneStyle'){s.cane=true;s.fan=false;if(s.bag==='clutch')s.bag='none';s.pose='resting'}});
const accessoryIcons:Record<string,string>={earrings:'<circle cx="12" cy="6" r="2"/><path d="M12 9Q4 15 12 22Q20 15 12 9Z"/>',beads:'<path d="M3 5Q3 26 12 25Q21 26 21 5" stroke-dasharray="2 3"/>',bracelet:'<ellipse cx="12" cy="15" rx="8" ry="5"/>',belt:'<path d="M2 12H22V18H2Z"/><rect x="9" y="11" width="6" height="8"/>',sunglasses:'<rect x="1" y="10" width="9" height="7" rx="2"/><rect x="14" y="10" width="9" height="7" rx="2"/><path d="M10 12H14"/>',watch:'<path d="M9 2H15V9H9ZM9 19H15V26H9Z"/><circle cx="12" cy="14" r="6"/>',cane:'<path d="M7 7Q7 1 13 3Q17 5 14 9L14 27"/>'};
for(const [id,icon]of Object.entries(accessoryIcons)){const b=get(id);const label=b.textContent;b.innerHTML=`<svg viewBox="0 0 24 30" width="25" height="32" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5">${icon}</svg><span>${label}</span>`;b.classList.add('accessory-tile')}
get('fan').onclick=()=>{commit(s=>{s.fan=!s.fan;if(s.fan){s.cane=false;s.pose='resting';if(s.bag==='clutch')s.bag='none'}});status('Fan uses a relaxed right-hand grip. Undo restores the previous look.')};
get('wrap').onchange=()=>commit(s=>s.wrap=get<HTMLSelectElement>('wrap').value as Look['wrap']);
get('wrapColour').onchange=()=>commit(s=>s.wrapColour=get<HTMLInputElement>('wrapColour').value);
get('bag').onchange=()=>commit(s=>{s.bag=get<HTMLSelectElement>('bag').value as Look['bag'];if(s.bag==='clutch'){s.cane=false;s.fan=false}});
get('colourTarget').onchange=()=>{colourTarget=get<HTMLSelectElement>('colourTarget').value;render()};
get('finish').onchange=()=>commit(s=>s.surfaces[surfaceKey(colourPart)].finish=get<HTMLSelectElement>('finish').value as 'matte'|'satin');
get('patternRotation').onchange=()=>commit(s=>s.surfaces[surfaceKey(colourPart)].rotation=Number(get<HTMLInputElement>('patternRotation').value));
get('hexColour').oninput=()=>{const v=get<HTMLInputElement>('hexColour').value.trim();if(/^#[0-9a-f]{6}$/i.test(v)){get('hexError').textContent='';writeColour(v.toLowerCase())}};
get('jumpsuitLeg').onchange=()=>commit(s=>s.bottom=get<HTMLSelectElement>('jumpsuitLeg').value as Look['bottom']);
get('hexColour').onchange=()=>{const v=get<HTMLInputElement>('hexColour').value.trim();if(!/^#[0-9a-f]{6}$/i.test(v)){get('hexError').textContent='Use # followed by six colour digits.';return}get('hexError').textContent='';writeColour(v.toLowerCase())};
syncColour=mountColour(readColour,writeColour);
const families:{label:string;values:Partial<Look>}[]=[
 {label:'Dress',values:{outfit:'dress',outer:'none',cut:'aline',length:'midi'}},
 {label:'Top & trousers',values:{outfit:'separates',top:'tee',bottom:'wide',outer:'none',length:'long'}},
 {label:'Blouse & skirt',values:{outfit:'separates',top:'blouse',bottom:'skirt',outer:'none',skirtShape:'aline',length:'midi'}},
 {label:'Jumpsuit',values:{outfit:'jumpsuit',bottom:'wide',outer:'none',length:'long'}},
 {label:'Coat & layers',values:{outfit:'separates',top:'shirt',bottom:'trousers',outer:'coat',length:'long'}},
 {label:'Tunic',values:{outfit:'tunic',outer:'none',length:'long'}},
 {label:'Agbada',values:{outfit:'agbada',outer:'agbada',length:'long'}}];
for(const f of families){const b=document.createElement('button');b.textContent=f.label;b.onclick=()=>{if(isEveryday(look))return;commit(s=>Object.assign(s,f.values,{canvasMode:'figure'}));selectPiece('colour');status(`${f.label} selected. Your colours and accessories are kept.`)};get('familyLaunch').append(b)}
for(const [id,mode]of [['editShape','shape'],['editColour','colour']] as const)get(id).onclick=()=>{document.querySelector<HTMLElement>('.inspector')!.dataset.mode=mode;get('editShape').setAttribute('aria-pressed',String(mode==='shape'));get('editColour').setAttribute('aria-pressed',String(mode==='colour'))};
placementUI=mountPlacement(canvas,{read:()=>look,commit,render,status,stopDrawing:()=>{drawMode=false;get('draw').setAttribute('aria-pressed','false')},select:id=>{colourPart=FIELDS[id] as typeof colourPart;colourTarget=id==='bag'?'bagColour':'piece';get<HTMLSelectElement>('colourTarget').value=colourTarget;get<HTMLSelectElement>('colourPart').value=colourPart;render()}});
everydayUI=mountEveryday({read:()=>look,commit,status,selected:()=>colourPart,select:field=>field==='accentColour'?selectBag():selectPiece(field)});
sketchImport=mountSketchImport({read:()=>look,commit,status});uxReady=true;fillCards();render();if(orderVersion){get('workspaceEyebrow').textContent=`REVISING ORDER DESIGN · VERSION ${orderVersion}`;get('reviewEyebrow').textContent=`ORDER DESIGN · VERSION ${orderVersion}`;get('reviewTitle').textContent='Review this update before sending.';status(`Working from order version ${orderVersion}. Changes stay on this device until you send them.`)}else if(sourceVersion){get('workspaceEyebrow').textContent=`TAILOR WORKING COPY · CUSTOMER VERSION ${sourceVersion}`;get('reviewEyebrow').textContent=`WORKING COPY · CUSTOMER VERSION ${sourceVersion}`;get('reviewTitle').textContent='Review your style plan before sharing.';status(`Customer design version ${sourceVersion} is open as your working copy. Review the sheet to send your style plan for approval.`)}else if(startMode()==='reference'){setRoom('reference');openMobileLibrary();status(recoveredDraft()?'Your latest draft is back. Add the photo or sketch you want to work from.':'Bring a look you already have, then describe what to keep and change.')}else if(startMode()==='saved'){get<HTMLDialogElement>('saveDialog').showModal();status('Choose a saved sketch to review for this brief.')}else if(recoveredDraft())status('Your latest draft is back.');else get<HTMLDialogElement>('welcome').showModal();if(storageNotice())status(storageNotice());

if(native){get('printReview').hidden=true;get<HTMLAnchorElement>('pngSave').onclick=event=>{event.preventDefault();const src=get<HTMLImageElement>('pngImage').src;void exportNative(src.split(',')[1]??'','image/png','png',true).then(()=>status('Image saved to your chosen folder.')).catch(error=>status(error.message))}}
