import { Colors, Fonts, FontSize, FontWeight, Radius, Shadow, Spacing } from '@/constants/theme'
import { StyleSheet } from 'react-native'

export const quoteDetailRow: import('react-native').ViewStyle = {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
}
export const quoteLabel: import('react-native').TextStyle = { fontSize: 14, color: Colors.inkLight }
export const quoteAmount: import('react-native').TextStyle = {
  fontSize: 22,
  fontWeight: '700',
  color: Colors.needleGreenDark,
}
export const quoteValue: import('react-native').TextStyle = {
  fontSize: 14,
  fontWeight: '600',
  color: Colors.ink,
}
const quoteFootnote: import('react-native').TextStyle = {
  fontSize: 12,
  color: Colors.midGrey,
  lineHeight: 18,
}

const styles = StyleSheet.create({
  flexOne: { flex: 1 },
  safe: { flex: 1, backgroundColor: Colors.bone },
  back: { paddingHorizontal: Spacing.xl, paddingTop: Spacing.md, paddingBottom: Spacing.sm },
  backText: { color: Colors.needleGreenDark, fontSize: FontSize.md, fontWeight: FontWeight.medium },
  scroll: { flex: 1 },
  content: { padding: Spacing.xl, gap: Spacing.md },
  quoteActionBar: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  quotePrimaryAction: { minWidth: 190, flexGrow: 1 },
  revisionReasonList: { gap: Spacing.sm },
  revisionFieldLabel: { fontSize: FontSize.sm, fontWeight: FontWeight.semibold, color: Colors.ink },
  revisionReasonGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  revisionReasonButton: { flexGrow: 0, maxWidth: '100%' },
  revisionError: { fontSize: FontSize.sm, lineHeight: 20, color: Colors.error },
  inlineWarningCard: {
    gap: 4,
    padding: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.kanteRust + '35',
    backgroundColor: Colors.kanteRustLight,
  },
  inlineWarningTitle: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.kanteRust,
  },
  inlineWarningBody: { fontSize: FontSize.xs, lineHeight: 18, color: Colors.inkLight },

  heading: {
    fontSize: FontSize.xxl,
    fontWeight: FontWeight.bold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  subheading: { fontSize: FontSize.sm, color: Colors.midGrey, marginTop: 4 },
  messageAction: {
    minHeight: 48,
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: 11,
    borderRadius: Radius.md,
    backgroundColor: Colors.needleGreenLight,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '30',
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  messageActionText: {
    flex: 1,
    fontSize: FontSize.md,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.semibold,
  },
  completionAction: {
    minHeight: 56,
    marginTop: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '35',
    backgroundColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  completionActionIcon: {
    width: 32,
    height: 32,
    borderRadius: Radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.needleGreenLight,
  },
  completionActionTitle: {
    fontSize: FontSize.sm,
    color: Colors.ink,
    fontWeight: FontWeight.semibold,
  },
  completionActionBody: { marginTop: 2, fontSize: FontSize.xs, color: Colors.midGrey },
  // Progress bar
  progressBar: { flexDirection: 'row', alignItems: 'flex-start', gap: 0 },
  progressStep: { flex: 1, alignItems: 'center', gap: 4, position: 'relative' },
  progressDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Colors.lightGrey,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: Colors.lightGrey,
  },
  progressDotDone: { backgroundColor: Colors.needleGreen, borderColor: Colors.needleGreen },
  progressDotActive: {
    backgroundColor: Colors.white,
    borderColor: Colors.needleGreen,
    borderWidth: 3,
  },
  progressCheck: { fontSize: 9, color: Colors.textInverse, fontWeight: FontWeight.bold },
  progressLine: {
    position: 'absolute',
    top: 8,
    left: '50%',
    right: '-50%',
    height: 2,
    backgroundColor: Colors.lightGrey,
    zIndex: -1,
  },
  progressLineDone: { backgroundColor: Colors.needleGreen },
  progressLabel: { fontSize: 8, color: Colors.midGrey, textAlign: 'center', lineHeight: 11 },
  progressLabelDone: { color: Colors.needleGreenDark, fontWeight: FontWeight.medium },

  // Status card
  statusCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    padding: 10,
    gap: 5,
    ...Shadow.sm,
  },
  statusNote: {
    fontSize: FontSize.xs,
    color: Colors.inkLight,
    fontStyle: 'italic',
    lineHeight: 18,
  },

  nextStepsCard: {
    backgroundColor: Colors.needleGreenLight,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    gap: Spacing.xs,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '30',
  },
  nextStepsTitle: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    color: Colors.needleGreenDark,
    marginBottom: 4,
    fontFamily: Fonts.display,
  },
  nextStepsItem: { fontSize: FontSize.xs, color: Colors.inkLight, lineHeight: 18 },
  progressPhoto: {
    width: '100%',
    height: 156,
    borderRadius: Radius.md,
    backgroundColor: Colors.boneDeep,
  },
  statusHelp: { fontSize: 11, color: Colors.inkLight, lineHeight: 17 },
  statusEta: { fontSize: 11, color: Colors.midGrey },

  // Video call card
  videoCallCard: {
    backgroundColor: Colors.boneDeep,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    gap: Spacing.sm,
    borderWidth: 1.5,
    borderColor: Colors.needleGreen,
  },
  videoCallTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  consultationFeeText: {
    fontSize: FontSize.sm,
    color: Colors.ink,
    fontWeight: FontWeight.semibold,
  },
  orderTypePill: {
    marginTop: Spacing.sm,
    alignSelf: 'flex-start',
    backgroundColor: Colors.needleGreenLight,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
  },
  orderTypePillText: {
    fontSize: FontSize.xs,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  videoCallHint: { fontSize: FontSize.sm, color: Colors.inkLight, lineHeight: 20 },

  // Modal shell
  modalSafe: { flex: 1, backgroundColor: Colors.bone },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Colors.lightGrey,
  },
  modalClose: {
    color: Colors.needleGreenDark,
    fontSize: FontSize.md,
    fontWeight: FontWeight.medium,
    width: 60,
  },
  modalTitle: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  modalScroll: { flex: 1 },
  modalContent: { padding: Spacing.xl, gap: Spacing.xl },

  // Collection code
  collectionCard: {
    backgroundColor: Colors.needleGreenLight,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    gap: Spacing.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.needleGreen + '40',
  },
  collectionTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: Colors.ink,
    textAlign: 'center',
    fontFamily: Fonts.display,
  },
  collectionEyebrow: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: Colors.needleGreenDark,
    letterSpacing: 1.4,
  },
  collectionHint: {
    fontSize: FontSize.sm,
    color: Colors.inkLight,
    textAlign: 'center',
    lineHeight: 20,
  },
  collectionExpiry: { fontSize: FontSize.xs, color: Colors.inkLight, textAlign: 'center' },
  codeBox: { flexDirection: 'row', gap: Spacing.md },
  codeDigit: {
    width: 56,
    height: 72,
    borderRadius: Radius.md,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadow.md,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '30',
  },
  codeDigitText: { fontSize: 32, fontWeight: FontWeight.bold, color: Colors.needleGreenDark },
  collectionInstruction: { fontSize: FontSize.sm, color: Colors.inkLight },
  disputeLink: { fontSize: FontSize.sm, color: Colors.kanteRust, fontWeight: FontWeight.medium },

  // Timeline
  section: { gap: Spacing.sm },
  sectionTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  timeline: { gap: 0, paddingLeft: Spacing.xs },
  timelineItem: { flexDirection: 'row', gap: 9, paddingBottom: 10 },
  timelineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.needleGreen,
    marginTop: 5,
    flexShrink: 0,
  },
  timelineContent: { flex: 1, gap: 2 },
  timelineStage: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  timelineNote: { fontSize: 11, color: Colors.inkLight, fontStyle: 'italic', lineHeight: 16 },
  timelinePhoto: {
    width: '100%',
    height: 176,
    borderRadius: Radius.md,
    backgroundColor: Colors.boneDeep,
    marginTop: Spacing.xs,
    marginBottom: 2,
    overflow: 'hidden',
  },
  timelineDate: { fontSize: 10, color: Colors.midGrey },

  // Tracking
  trackingRow: {
    backgroundColor: Colors.white,
    borderRadius: Radius.md,
    padding: Spacing.md,
    gap: Spacing.md,
    ...Shadow.sm,
  },
  trackingAction: {
    width: '100%',
  },
  trackingLabel: { fontSize: FontSize.sm, color: Colors.inkLight },
  trackingNumber: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.needleGreenDark,
  },
  summaryLine: { flexDirection: 'row', justifyContent: 'space-between', gap: Spacing.md },
  summaryLineLabel: { fontSize: FontSize.sm, color: Colors.midGrey },
  summaryLineValue: {
    flex: 1,
    textAlign: 'right',
    fontSize: FontSize.sm,
    color: Colors.ink,
    fontWeight: FontWeight.medium,
  },
  dossierList: { gap: Spacing.sm },
  dossierRowStacked: { gap: 6 },
  dossierRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  dossierStackedText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
    color: Colors.ink,
    lineHeight: 20,
  },
  dossierLinkText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
    color: Colors.needleGreenDark,
    lineHeight: 20,
  },
  dossierMediaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs },
  dossierMediaTile: {
    width: '31%',
    aspectRatio: 1,
    borderRadius: Radius.md,
    overflow: 'hidden',
    backgroundColor: Colors.boneDeep,
  },
  dossierMediaImage: { width: '100%', height: '100%' },
  styleChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  styleChip: {
    borderRadius: Radius.full,
    backgroundColor: Colors.needleGreenLight,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
  },
  styleChipText: {
    fontSize: FontSize.xs,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.semibold,
  },
  helperText: { fontSize: FontSize.sm, color: Colors.midGrey, lineHeight: 20 },
  quoteFootnote,
  supportCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    padding: 10,
    gap: 6,
    ...Shadow.sm,
  },
  disclosureCard: {
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.boneDeep,
    shadowOpacity: 0,
  },
  disclosureHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  disclosureCopy: { flex: 1, gap: 3 },
  disclosureSummary: { fontSize: FontSize.xs, color: Colors.midGrey, lineHeight: 18 },
  disclosureAction: {
    color: Colors.needleGreenDark,
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
  },
  disclosureBody: {
    paddingTop: Spacing.xs,
    gap: 6,
  },
  supportCardTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  supportCardWarning: {
    borderWidth: 1,
    borderColor: Colors.kanteRust + '40',
  },
  materialDecisionSuccess: {
    borderWidth: 1,
    borderColor: Colors.needleGreen + '40',
    backgroundColor: Colors.needleGreenLight,
  },
  supportMetaList: { gap: 6 },
  supportStatusBadge: {
    alignSelf: 'flex-start',
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
  },
  supportStatusWarning: { backgroundColor: Colors.kanteRustLight },
  supportStatusSuccess: { backgroundColor: Colors.needleGreenLight },
  supportStatusText: { fontSize: FontSize.xs, fontWeight: FontWeight.semibold },
  supportStatusTextWarning: { color: Colors.kanteRust },
  supportStatusTextSuccess: { color: Colors.needleGreenDark },
  supportBodyText: { fontSize: FontSize.xs, color: Colors.inkLight, lineHeight: 18 },
  supportWarningText: { fontSize: FontSize.xs, color: Colors.kanteRust, lineHeight: 18 },
  supportHint: { fontSize: 11, color: Colors.midGrey, lineHeight: 17 },
  materialProofMissing: {
    gap: 4,
    borderWidth: 1,
    borderColor: Colors.kanteRust + '40',
    backgroundColor: Colors.kanteRustLight,
    borderRadius: Radius.md,
    padding: Spacing.md,
  },
  materialProofMissingTitle: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.kanteRust,
  },
  inlineActions: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, alignItems: 'center' },
  decisionLink: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '45',
    backgroundColor: Colors.needleGreenLight,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
  },
  decisionLinkText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    color: Colors.needleGreenDark,
  },
  decisionFeedbackBody: { fontSize: FontSize.md, lineHeight: 24, color: Colors.ink },
  groupMemberList: { gap: Spacing.sm, marginTop: Spacing.xs },
  groupMemberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    borderRadius: Radius.md,
    padding: Spacing.sm,
  },
  groupMemberCopy: { flex: 1, gap: 2 },
  groupMemberName: { fontSize: FontSize.sm, color: Colors.ink, fontWeight: FontWeight.semibold },
  groupMemberStatus: { fontSize: FontSize.xs, color: Colors.midGrey },
  groupInviteButton: {
    borderRadius: Radius.full,
    backgroundColor: Colors.needleGreen,
    paddingVertical: 7,
    paddingHorizontal: Spacing.md,
  },
  groupInviteButtonText: {
    fontSize: FontSize.xs,
    color: Colors.textInverse,
    fontWeight: FontWeight.semibold,
  },
  groupMemberBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: Radius.full,
    backgroundColor: Colors.needleGreenLight,
    paddingVertical: 6,
    paddingHorizontal: Spacing.sm,
  },
  groupMemberBadgeText: {
    fontSize: FontSize.xs,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.semibold,
  },
  inlineDecisionCard: {
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.lg,
    backgroundColor: Colors.bone,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
  },
  inlineDecisionTitle: {
    fontSize: FontSize.sm,
    color: Colors.ink,
    fontWeight: FontWeight.semibold,
  },
  measurementConfirmGuideList: { gap: Spacing.xs },
  measurementConfirmGuideCard: {
    borderRadius: Radius.md,
    padding: Spacing.sm,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.kanteRust + '35',
  },
  measurementConfirmGuideTitle: {
    fontSize: FontSize.xs,
    color: Colors.kanteRust,
    fontWeight: FontWeight.semibold,
  },
  measurementConfirmGuideText: {
    marginTop: 3,
    fontSize: 11,
    color: Colors.inkLight,
    lineHeight: 16,
  },
  handoffIssueCard: {
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.lg,
    backgroundColor: Colors.bone,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
  },
  handoffIssueHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  handoffIssueTitle: {
    flex: 1,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
  },
  handoffStatusPill: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: Radius.full,
    backgroundColor: Colors.needleGreenLight,
  },
  handoffStatusPillEscalated: {
    backgroundColor: Colors.accentLight,
  },
  handoffStatusText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    color: Colors.needleGreenDark,
  },

  // Fabric tracking input
  trackingHint: { fontSize: FontSize.sm, color: Colors.inkLight, lineHeight: 20 },
  fabricInputRow: { flexDirection: 'row', gap: Spacing.sm, alignItems: 'center' },
  fabricTrackingAction: {
    gap: Spacing.sm,
    paddingTop: Spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Colors.lightGrey,
  },
  fabricInput: {
    flex: 1,
    backgroundColor: Colors.white,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    fontSize: FontSize.md,
    color: Colors.ink,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    ...Shadow.sm,
  },
  fabricSaveBtn: {
    backgroundColor: Colors.needleGreen,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    minWidth: 64,
    alignItems: 'center',
  },
  fabricSaveBtnDisabled: { backgroundColor: Colors.lightGrey },
  fabricSaveBtnText: {
    color: Colors.textInverse,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
  },
  fabricSavedNote: { fontSize: FontSize.xs, color: Colors.midGrey },
  fabricApprovalCard: {
    gap: Spacing.sm,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.bone,
    padding: Spacing.sm,
  },
  fabricApprovalImage: {
    width: '100%',
    height: 180,
    borderRadius: Radius.md,
    backgroundColor: Colors.boneDeep,
  },
  fabricApprovalActions: { gap: Spacing.sm },

  reviewCta: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    ...Shadow.sm,
    borderWidth: 1,
    borderColor: Colors.statusPending + '40',
  },
  reviewCtaInner: { gap: 3 },
  reviewCtaTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.ink,
    fontFamily: Fonts.display,
  },
  reviewCtaHint: { fontSize: FontSize.sm, color: Colors.inkLight },
  reviewCtaArrow: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.statusPending,
  },

  messageCta: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: Colors.white,
    padding: Spacing.lg,
    borderTopWidth: 1,
    borderTopColor: Colors.lightGrey,
    paddingBottom: Spacing.xxl,
  },
  scrollContent: {
    paddingBottom: 480,
  },

  sentBanner: {
    backgroundColor: Colors.needleGreenLight,
    borderRadius: Radius.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '35',
  },
  sentBannerText: {
    fontSize: FontSize.sm,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.medium,
  },

  stateWrap: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: Spacing.xl },
  stateCard: {
    width: '100%',
    maxWidth: 440,
    backgroundColor: Colors.white,
    borderRadius: Radius.xl,
    padding: Spacing.lg,
    gap: Spacing.md,
    alignItems: 'center',
    ...Shadow.lg,
  },
  stateEyebrow: {
    fontSize: FontSize.xs,
    color: Colors.needleGreenDark,
    fontWeight: FontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  stateTitle: {
    fontSize: FontSize.md,
    color: Colors.ink,
    fontWeight: FontWeight.bold,
    textAlign: 'center',
    fontFamily: Fonts.display,
  },
  stateHint: { fontSize: FontSize.sm, color: Colors.inkLight, textAlign: 'center', lineHeight: 21 },
  backLink: { color: Colors.needleGreenDark, fontSize: FontSize.md, fontWeight: FontWeight.medium },
  retryBtn: {
    backgroundColor: Colors.needleGreen,
    borderRadius: Radius.full,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.xxxl,
  },
  retryBtnText: {
    color: Colors.textInverse,
    fontWeight: FontWeight.semibold,
    fontSize: FontSize.sm,
  },
  secondaryBtn: {
    backgroundColor: Colors.white,
    borderColor: Colors.lightGrey,
    borderRadius: Radius.full,
    borderWidth: 1,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.xxxl,
  },
  secondaryBtnText: { color: Colors.ink, fontWeight: FontWeight.semibold, fontSize: FontSize.sm },

  // Pre-production waiting bar
  preProductionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  preProductionDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: Colors.warning },
  preProductionLabel: {
    fontSize: FontSize.sm,
    color: Colors.midGrey,
    fontWeight: FontWeight.medium,
  },

  // Dispute entry
  disputeEntry: { alignItems: 'center', paddingTop: Spacing.sm },
  disputeEntryText: {
    fontSize: FontSize.sm,
    color: Colors.kanteRust,
    fontWeight: FontWeight.medium,
  },

  // Quote review extras
  escrowNote: {
    backgroundColor: Colors.needleGreenLight,
    borderRadius: Radius.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.needleGreen + '35',
  },
  escrowNoteText: { fontSize: FontSize.xs, color: Colors.inkLight, lineHeight: 18 },
  consultationCallChoices: { flexDirection: 'row', gap: Spacing.sm },
  consultationCallChoice: {
    flex: 1,
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    borderRadius: Radius.md,
    backgroundColor: Colors.white,
  },
  consultationCallChoiceActive: {
    borderColor: Colors.needleGreen,
    backgroundColor: Colors.needleGreenLight,
  },
  consultationCallChoiceText: {
    color: Colors.ink,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
  },
})

export { styles }
